lucet-wasi/build.rs

Since we're doing the `sed` shenanigans to preprocess this header file, the original header wasn't getting marked for rebuilds by `bindgen`. Bug found by @jedisct1

Properly mark <wasi/core.h> for rebuilds

---

README.md

A handful of folks have hit this :( . Blog post update is also in flight

README: note submodules are required in environment setup

---

lucet-wasi/build.rs

if something in lucet-wasi's build.rs fails right now, it can result in bindgen just not running and odd failures about missing methods later on

teach lucet-wasi to be smarter about build failure modes

---

lucetc/src/lib.rs

Also allow the linker and its flags to be overridden using standard environment variables.

Make lucetc work on macOS

---

lucet-runtime/lucet-runtime-internals/src/region/mmap.rs

Needless to say that clearing the whole heap has some performance implications :(

Add another explicit page zeroing when MADV_DONTNEED is not enough

---

Dockerfile

bump rust to 1.34.2

---

lucet-wasi/src/hostcalls/fs.rs
lucet-wasi/src/hostcalls/misc.rs
lucet-wasi/src/memory.rs

Similar to what was done in wasi-common, make `dec_slice_of` return
a slice rather than a pionter-length pair.
Add a mutable version, and use immutable slices as much as possible.
Mark codec functions safe.

Make users of `dec_slice_of` safe, make codecs safe

---

helpers/install.sh

The installation script now tries to compile a minimal program to verify that a a compatible compilation toolchain exists.
We also try to deal with the fact that some environments require a version suffix on clang and/or llvm tools (ex: Ubuntu 19.10), but some don't (ex: macOS).
The script produces more verbose output about what it is doing and what may be missing for a successful installation.

Find how a wasm32-wasi compatible LLVM and Clang were installed

---

lucet-wasi/src/hostcalls/fs.rs

POSIX mentions that `readlink(2)` and `readlinkat(2)` can accept an empty buffer.
As usual, Linux doesn't follow the specification, and returns `EINVAL` if the buffer length is zero.
Work around this by allocating a dummy buffer if the length is zero.
Bug originally spotted in wasi-common, but different fix.

wasi_path_readlink: do not return EINVAL if an empty buffer is supplied

---

benchmarks/lucet-benchmarks/Cargo.toml
lucet-analyze/Cargo.toml
lucet-idl/Cargo.toml
lucet-module-data/Cargo.toml
lucet-runtime/Cargo.toml
lucet-spectest/Cargo.toml
lucet-wasi-fuzz/Cargo.toml
lucet-wasi-sdk/Cargo.toml
lucet-wasi/Cargo.toml
lucetc/Cargo.toml

Add description, homepage, use the same license everywhere, reorder, add the webassembly category for crates.io

Update the Cargo.toml properties

---

helpers/lucet-toolchain-tests/signature.sh

This makes the script work when the `release` directory is present, but does not contain `lucetc` or `lucet-wasi`.

Make the signature testing script work with partial target dirs

---

lucet-wasi/src/main.rs

In `lucetc`, units are optional.
In `lucet-wasi`, units are mandatory. Not having a trailing "B" after a size given in bytes yields a confusing message about the size being invalid.
Parse sizes the same way. So that, e.g. the same value can be used with `--reserved-size` and `--max-heap-size`.

Parse sizes in lucet-wasi and lucetc the same way

---

lucetc/src/decls.rs

Don't just unwrap() on references to non-local tables

---

lucet-spectest/tests/wasm-spec.rs

specs that didn't pass before, pass now!

Spectest comment updates

---

lucet-builtins/wasmonkey/README.md
lucet-wasi/tests/guests/duplicate_import.wat
lucetc/tests/wasm/duplicate_imports.wat

Fix a few typos

---

lucet-runtime/lucet-runtime-internals/src/context/context_asm.S
lucet-runtime/lucet-runtime-internals/src/context/mod.rs

Refactor Context::init and document initial guest stacks more

---

lucet-runtime/lucet-runtime-internals/src/instance/signals.rs

This is a pair of changes to add some wiggle room in our signal handler and avoid overflowing signal stacks.
First, move a stack-heavy part of `handle_signal` to a thunk, so debug builds defer reserving that region's stack use until we reach it, freeing ~5kb of stack for other paths through the signal handler.
Second, add a guard page under the guest's signal stack, to catch sigstack overflow when handling guest faults.

Signal handling tweaks

---

Cargo.lock
lucet-analyze/Cargo.toml
lucet-builtins/wasmonkey/Cargo.toml
lucetc/Cargo.toml

there were 4 different versions across the project! shameful.

use goblin 0.0.24 everywhere

---

Makefile
lucet-wasi-sdk/tests/lucetc.rs

This was introduced by #331, so has only been merged for a few days.

Fix bug that was limiting the number of tests that were run

---

lucetc/src/main.rs

[lucetc] restore output for the underlying cause of `lucetc::Error`s

---

Cargo.lock
benchmarks/lucet-benchmarks/Cargo.toml
lucet-module/Cargo.toml
lucet-objdump/Cargo.toml
lucet-runtime/Cargo.toml
lucet-runtime/lucet-runtime-internals/Cargo.toml
lucet-runtime/lucet-runtime-tests/Cargo.toml
lucet-spectest/Cargo.toml
lucet-validate/Cargo.toml
lucet-wasi-fuzz/Cargo.toml
lucet-wasi-sdk/Cargo.toml
lucet-wasi/Cargo.toml
lucetc/Cargo.toml

The handling of CPU features is semver-breaking.

Bump crate versions to 0.4.0

---

lucet-builtins/wasmonkey/src/bin/config/mod.rs
lucet-builtins/wasmonkey/src/bin/wasmonkey.rs
lucet-idl/lucet-idl-test/src/main.rs
lucet-idl/src/main.rs
lucet-spectest/src/main.rs
lucetc/lucetc/main.rs
lucetc/lucetc/options.rs

Use app_from_crate!() instead of hardcoding clap base parameters

---

lucet-runtime/lucet-runtime-internals/src/instance.rs

While taking a look at the runtime internals crate, I saw some various lint warnings that were easy fixes. This patch only touches warnings related to [long integer constants](https://rust-lang.github.io/rust-clippy/master/#unreadable_literal), [or calls](https://rust-lang.github.io/rust-clippy/master/#or_fun_call), [redundant field names](https://rust-lang.github.io/rust-clippy/master/#redundant_field_names), and [map unit functions](https://rust-lang.github.io/rust-clippy/master/#redundant_field_names).

Miscellaneous Lint Fixes in Lucet Instance

---

lucet-module/src/signature.rs

No functionality change, just replaces a few conditional `continue` statements with `filter`. Seemed like a small change that helps w/ the readability of this loop :slightly_smiling_face: 
:rose: :potable_water: :woman_farmer:

clean up `symbol_data` control flow

---

lucetc/src/compiler/cpu_features.rs

When I merged the good work done in #390 with #374, I missed a spot.
See: https://github.com/bytecodealliance/lucet/pull/390/files#diff-bafa9665c27394aad42e04c9fca6a8aaL195-L196

Fix bad merge in cpu_features.rs

---

CHANGELOG.md
Cargo.lock
benchmarks/lucet-benchmarks/Cargo.toml
lucet-module/Cargo.toml
lucet-objdump/Cargo.toml
lucet-runtime/Cargo.toml
lucet-runtime/lucet-runtime-internals/Cargo.toml
lucet-runtime/lucet-runtime-macros/Cargo.toml
lucet-runtime/lucet-runtime-tests/Cargo.toml
lucet-spectest/Cargo.toml
lucet-validate/Cargo.toml
lucet-wasi-fuzz/Cargo.toml
lucet-wasi-sdk/Cargo.toml
lucet-wasi/Cargo.toml
lucetc/Cargo.toml

Adapted from #424, this pulls in the latest changes and makes the changelog format match. Thank you, @DavidM-D!

0.6.1 release

---

benchmarks/shootout/Makefile

specifically, pass correct form of "as optimized as possible please" flag to lucet

Fix Sightglass' Lucet flags

---

lucet-runtime/lucet-runtime-internals/src/alloc/tests.rs
lucet-runtime/lucet-runtime-internals/src/instance.rs

Thank you @fst-crenshaw for discovering this bug, and talking through the solution to help make it more robust 🎉
This fix:
- Defers the early error return until after the `CURRENT_INSTANCE` is set back to `None`, and
- Sets the instance state back to `Ready` if it hasn't advanced past `Running`.
Also adds additional assertions to the tests that intentionally try running with an insufficient signal stack, to make sure that both the instance and the thread-local variable are left in reasonable states.

🔧 fix #455: handle early returns while setting up an instance run

---

lucet-runtime/lucet-runtime-internals/src/alloc/mod.rs

Add a derivation of the Clone trait to AllocStrategy.

Add a derivation of the Clone trait to AllocStrategy.

---

docs/src/Compiling-on-Linux.md
docs/src/Compiling-on-macOS.md

Doc: add --recursive and update the WASI SDK version

---

CHANGELOG.md

add `hostcall_reservation` feature to CHANGELOG.md

---

docs/src/Compiling-on-Linux.md

Added correct path for ARCH linux.
Please review

Compling: MD; add a path for ARCH linux

---

lucet-runtime/lucet-runtime-internals/src/future.rs

Also adds a test to ensure that both `run_async()` and `run_async_start()` impl `Send`.

📨 Make `InstanceHandle::run_async_start()` future impl `Send`

---

docs/src/Overview.md

Documentation: fix the "Getting Started" link

---

README.md

Terrarium was an early experiment, and is no longer supported

readme: Lucet powers Fastly Compute@Edge
