- config.inc
- devenv_build_container.sh
- devenv_run.sh
- devenv_setenv.sh
- devenv_start.sh
- devenv_stop.sh
I'm using bash on Ubuntu 18.04 LTS.
Without this modification, I got the following error when running `source devenv_setenv.sh`
```
$ source devenv_setenv.sh
dirname: invalid option -- 'b'
Try 'dirname --help' for more information.
-bash: /config.inc: No such file or directory
Command '' not found, but can be installed with:
sudo apt install libpam-mount
sudo apt install openssh-server
sudo apt install openvswitch-common
sudo apt install openvswitch-switch
sudo apt install php-common
sudo apt install bpfcc-tools
sudo apt install burp
sudo apt install cryptmount
sudo apt install dolphin-emu
sudo apt install mailutils-mh
sudo apt install mmh
sudo apt install nmh
Unable to run commands in the container
```
> Support bash in devenv scripts

- README.md
This adds a link to SECURITY.md to the bottom of README.md, but above the vulnerability reporting section. If you'd like to do something different just let me know.
> Add link to security.md to readme.md

- lucet-wasi/src/main.rs
`multiple(true)` for the --dir option doesn't play well with modules also accepting multiple values for their arguments, resulting in convoluted command lines when both have to be used simultaneously.
This fixes it as recommended in the clap documentation for that very situation. `Arg::number_of_values(1)` doesn't prevent `--dir a1:b1 --dir a2:b2` from being used, but prevents `--dir a1:b1 a2:b2` to remove ambiguities.
> lucet-wasi: use number_of_values(1) for the --dir option

- Cargo.lock
- lucet-runtime/lucet-runtime-internals/src/alloc/mod.rs
- lucet-runtime/lucet-runtime-internals/src/alloc/tests.rs
- lucet-runtime/lucet-runtime-internals/src/module.rs
- lucet-runtime/lucet-runtime-internals/src/region/mmap.rs
- lucet-wasi/Cargo.toml
- lucet-wasi/src/main.rs
- lucetc/src/compiler/data.rs
- lucetc/src/compiler/entity/mod.rs
- lucetc/src/compiler/memory.rs
- lucetc/src/compiler/module_data.rs
- lucetc/src/lib.rs
- lucetc/src/main.rs
- lucetc/src/options.rs
- lucetc/src/program/memory.rs
- lucetc/src/program/mod.rs
- lucetc/tests/wasm.rs
This adds command-line parameters to `lucet-wasi` to control the memory limits, and raises the default values of those limits substantially. Most users will only ever need to turn them down, not up.
Also, this reworks the way reserved size is set in `lucetc` to provide fewer surprises; see https://github.com/fastly/lucet/pull/77/commits/b563370b6b9e1b5821f2bfe288ec956da953638f.
Finally, this switches to relying on `madvise` to zero the instance heap when an instance is reset or created, substantially improving performance for programs with large initial heaps.
Closes #74 and #76
> Add CLI configuration for memory limits and improve performance for large initial heaps

- lucetc/src/compiler/data.rs
`https://webassembly.github.io/spec/syntax/modules.html#data-segments` is not found.
> Fix url in comments

- benchmarks/shootout/Makefile
Some options used here seem to have bitrotted some. `--reserved-size` was split into `--{min,max}-reserved-size` but it looks to be that the spirit of that is best expressed as `--max-reserved-size` now
> Fix benchmarks/shootout makefile

- Dockerfile
- devenv_build_container.sh
- devenv_run.sh
- devenv_start.sh
We end up with two images.
The former being just the base development environment, suitable for CI.
The later having the release builds populated in /opt/lucet.
This is the one we can upload to the Docker Hub, as people can use it to get immediately started with Lucet without having to recompile it.
Also remove the wasi debian package after installation by the way.
> Build a "lucet" layer on top of "lucet-dev"

- lucet-wasi-sdk/src/lib.rs
it appears that as of this moment both of the following are true:
* lld's wasm linker may deadlock if linking with threads enabled
* lld's wasm linker builds with threads enabled by default
some references found in tracking this down:
https://bugs.llvm.org/show_bug.cgi?id=37064
the following looks to not be wasm-related in particular:
https://bugs.llvm.org/show_bug.cgi?id=34806
but similar patterns seem to exist in the wasm driver used by lld,
even if they've since been fixed for other targets.
(this should fix travis' flaky builds since they were all due to `ld` hangs)
> lucet-wasi-sdk: disable threading in lld (wasm-ld)

- .travis.yml
- devenv_run.sh
- devenv_start.sh
Old versions of Docker, such as the one used in Travis images, didn't support regular expressions in filters.
Add a workaround for this in order to support a wider range of distributions.
Simplify Travis build rules by the way.
> Compatibility with old versions of Docker

- .cargo/config
The MacOS linker requires `-export_dynamic` instead of `-export-dynamic`.
Due to `-export-dynamic` being in the global `cargo` config, tools from Lucet that could be compiled on macOS cannot be compiled any more.
This also prevented RLS from working properly.
-rdynamic works everywhere.
> Replace -W,-export-dynamic with -rdynamic

- lucet-runtime/lucet-runtime-tests/Cargo.toml
This crate only defines test functions for `lucet-runtime`.
As a result, it includes a (and possibly more in the future) reference to
functions in `lucet-runtime` (currently, `lucet_vmctx_get_heap`), and cannot be
built independently of `lucet-runtime`. `cargo test` will attempt to do exactly
this and result in an unhelpful build error about undefined symbols, while
trying to produce a binary to test that is tightly coupled to `lucet-runtime`
anyway.
This change disables tests for `lucet-runtime-tests` to keep cargo from trying
to build tests for this crate.
For reference, the build error mentioned above looks something like:
```
error: linking with `cc` failed: exit code: 1 
|
= note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" [long list of arguments omitted]
= note: …
```
> Disable "cargo test" for lucet-runtime-tests

- README.md
In [this PR](https://github.com/fastly/lucet/pull/49), `lucet_setenv` was moved to `devenv_setenv`. So now you will see this error.
```
bash: /opt/lucet/bin/lucet_setenv.sh: No such file or directory
```
> Fix setenv script name

- .gitattributes
the assets/*.png files were getting CRLF'd up during rebases
> gitattributes: note that png and jpg are binary files

- README.md
- benchmarks/lucet-benchmarks/src/seq.rs
- lucet-runtime/lucet-runtime-internals/Cargo.toml
- lucet-runtime/lucet-runtime-internals/src/alloc/mod.rs
- lucet-runtime/lucet-runtime-internals/src/c_api.rs
- lucet-runtime/lucet-runtime-internals/src/context/context_asm.S
- lucet-runtime/lucet-runtime-internals/src/instance.rs
- lucet-runtime/lucet-runtime-internals/src/instance/signals.rs
- lucet-runtime/lucet-runtime-internals/src/lib.rs
- lucet-runtime/lucet-runtime-internals/src/region/mmap.rs
- lucet-runtime/lucet-runtime-internals/src/sysdeps/linux.rs
- lucet-runtime/lucet-runtime-internals/src/sysdeps/macos.rs
- lucet-runtime/lucet-runtime-internals/src/sysdeps/mod.rs
- lucet-runtime/lucet-runtime-tests/src/guest_fault.rs
- lucet-runtime/lucet-runtime-tests/src/guest_fault/traps.S
- lucet-wasi-sdk/src/lib.rs
- lucet-wasi/build.rs
- lucet-wasi/src/host.rs
- lucet-wasi/src/hostcalls.rs
This improves portability of the toolchain to non-Linux systems, and adds preliminary support for running Lucet natively on macOS.
* Make `ucontext` a Rust structure instead of using the Linux-specific structure directly. `nix` and `libc` don't have a definition for `ucontext_t` and its dependencies on macOS yet, so we have to provide it for now. I'll send a PR to these in order to have this merged upstream.
* Make assembly code compatible with non-ELF (namely, Mach-O) systems.
* Don't require `wasi-sdk` to be present. `clang` and the wasi sysroot can have different roots (defined in `CLANG_ROOT` and `WASI_SYSROOT`). They are still derived from the `wasi-sdk` path by default. So that the system-provided LLVM installation can be used directly on macOS and Linux distributions with …
> Improve portability (macOS port, part 2)

- .gitignore
some rude CI system we use puts cores into $PWD, and the lucet-runtime test suite forks two processes that are intended to abort. this gitignore makes the presence of those files not flag the git diff as dirty.
> gitignore: core.*

- helpers/install.sh
- lucet-builtins/Makefile
- lucet-runtime/include/lucet.h
- lucet-runtime/include/lucet_types.h
- lucet-runtime/lucet-runtime-internals/src/sysdeps/macos.rs
- lucet-runtime/lucet-runtime-tests/src/build.rs
- lucet-wasi-sdk/src/lib.rs
- lucetc/tests/wasi-sdk.rs
Instead of hard-coded, linker-specific command-line flags, define a portable set of options to express the intent.
These options are then converted into the correct set of command-line flags for the given linker.
We may eventually want to do the same thing for the compiler, but this is not really necessary for now since clang is all we support.
Also make `ucontext` inclusion more portable to non-glibc environments.
> Replace hard-coded link flags with portable link options

- lucet-wasi/include/lucet_wasi.h
- lucet-wasi/tests/guests/getrusage.c
* fix the lucet-wasi C API header warning thrown with strict prototypes
* fix test that uses getrusage, prototype temporarily unavailable due to wasi-sysroot bug fixed upstream. only effects using wasi-sdk release 4
> lucet-wasi header fixups

- Dockerfile
Just upgrades the package installed in the Dockerfile. The only fix required went in as part of #146
> Upgrade to wasi-sdk 4.0

- lucet-wasi/src/hostcalls.rs
`fd_read()` should not close the descriptor after a short read.
`EOF` is only reached when `readv(2)` returns `0`.
Fixes #128
> Short reads from readv(2) don't mean EOF

- lucet-runtime/lucet-runtime-internals/src/module/dl.rs
Here's another variant for an undefined symbol :(
> Unfortunately, error strings are not very portable

- lucet-runtime/lucet-runtime-internals/src/instance/signals.rs
- lucet-runtime/lucet-runtime-tests/src/guest_fault.rs
`sigaltstack(2)`'s second argument is not exactly the "old" `stack_t` when registering a stack for signal handling.
Only the flags are supposed to be read, in order to know whether we currently are on the alternative stack, and/or if one has been set.
The regular stack is automatically restored after a signal handler returns.
Disabling an alternative stack should be done by passing the `SS_DISABLE` flag, not necessarily by copying what was returned in the optional second argument to the function.
Even on Linux, the address of the "old" `stack_t` appears to be always set to `NULL`, but it may be undefined. So it is not relevant, and is ignored when `SS_DISABLE` is set anyway.
On MacOS, providing the stack size is required, even with `SS_DISABLE`.
This commit changes a few things.
First, in …
> Fix sigaltstack(2) usage in lucet-runtime

- lucet-runtime/lucet-runtime-internals/src/instance/signals.rs
This was previously causing the Lucet sigstack to stay installed after an instance returns, as long
as another instance was running.
> Make sigaltstack restore on a per-thread basis

- lucetc/src/compiler.rs
- lucetc/src/function_manifest.rs
- lucetc/src/output.rs
- lucetc/src/stack_probe.rs
This provides a complete list of functions in the artifact, rather than what we were using - the subset that happened to possibly trap.
~(CI will fail because this depends on a cranelift change)~ the change was merged!
> Build a complete function manifest

- lucet-runtime/lucet-runtime-internals/src/alloc/tests.rs
- lucet-runtime/lucet-runtime-internals/src/instance.rs
- lucet-runtime/src/c_api.rs
This was previously segfaulting if the region got dropped after the `mem::replace` line. Our tests
previously always had the region remain in scope, which is why we didn't catch it till now
> Zero out instance magic more safely

- lucet-runtime/lucet-runtime-internals/src/instance.rs
- lucet-runtime/lucet-runtime-internals/src/instance/siginfo_ext.rs
- lucet-runtime/lucet-runtime-internals/src/instance/signals.rs
`libc-0.2.54` added a new method to `Siginfo` that is identical, aside from an `unsafe` annotation, to our `si_addr` method in the `SiginfoExt` trait. However, it only works on Linux. We rename our method to `si_addr_ext` so that it works again.
Fixes #170
> lucet-runtime-internals: replace our own si_addr method with libc-0.2.54

- benchmarks/lucet-benchmarks/src/modules.rs
- benchmarks/lucet-benchmarks/src/par.rs
- benchmarks/lucet-benchmarks/src/seq.rs
- lucet-module-data/src/functions.rs
- lucet-module-data/src/lib.rs
- lucet-module-data/src/module_data.rs
- lucet-runtime/lucet-runtime-internals/src/instance.rs
- lucet-runtime/lucet-runtime-internals/src/module.rs
- lucet-runtime/lucet-runtime-internals/src/module/dl.rs
- lucet-runtime/lucet-runtime-internals/src/module/mock.rs
- lucet-runtime/lucet-runtime-tests/src/entrypoint.rs
- lucet-runtime/lucet-runtime-tests/src/globals.rs
- lucet-runtime/lucet-runtime-tests/src/guest_fault.rs
- lucet-runtime/lucet-runtime-tests/src/host.rs
- lucet-runtime/lucet-runtime-tests/src/memory.rs
- lucet-runtime/lucet-runtime-tests/src/stack.rs
- lucet-runtime/lucet-runtime-tests/src/start.rs
- lucet-runtime/lucet-runtime-tests/src/strcmp.rs
- lucet-runtime/src/c_api.rs
- lucet-runtime/src/lib.rs
- lucet-spectest/src/script.rs
- lucet-wasi-fuzz/src/main.rs
- lucet-wasi/src/main.rs
- lucet-wasi/tests/test_helpers/mod.rs
- lucetc/src/decls.rs
- lucetc/tests/wasi-sdk.rs
- lucetc/tests/wasm.rs
also uncomment parts of lucetc tests that are now expressible/testable
Adds FunctionIndex newtype instead of passing around raw u32, to help make the lifecycle of function indices clearer.
Overall this isn't too big, but is the last piece I wanted to have in module data before renaming, and spending a moment fixing up lucet-analyze to know about all the new stuff.
> Add function import/export information to module data

- README.md
- lucet-wasi/README.md
- All the syscalls have been implemented now
- Explain how to compile Lucet from scratch, on Linux and MacOS.
> Update lucet-wasi documentation, and the main documentation

- lucet-wasi/src/hostcalls/fs_helpers.rs
- lucet-wasi/tests/guests/fs.c
When traversing directories, we should keep the most recent file descriptor.
Add a test case originally triggering that bug.
Spotted by @kubkon -- thanks!
> Fix a path_get() bug with nested directories

- benchmarks/lucet-benchmarks/src/compile.rs
- benchmarks/lucet-benchmarks/src/par.rs
- benchmarks/lucet-benchmarks/src/seq.rs
- lucet-spectest/src/script.rs
- lucetc/src/compiler.rs
- lucetc/src/options.rs
- lucetc/tests/wasi-sdk.rs
- lucetc/tests/wasm.rs
Just call them `0`, `1` and `2` to avoid confusion, and `fast`, currently an alias for `2`.
Alternative names such as `size` can be added later.
> Rename lucetc optimization levels

- lucetc/src/compiler.rs
- lucetc/src/decls.rs
- lucetc/src/function.rs
- lucetc/src/module.rs
- lucetc/src/output.rs
- lucetc/src/runtime.rs
- lucetc/src/stack_probe.rs
- lucetc/tests/wasm.rs
Runtime functions were not getting their supporting metadata (trap tables, names, ..) added to module data, which I think is mostly harmless, but violates some assumptions I'd made about what data is present in module data and function manifests. Specifically, that all functions in the module are present, and have a signature.
> Emit function information for lucetc-provided functions

- helpers/install.sh
- When used interactively, give a chance to the user to change the destination directory, and provide feedback after installation
- Add support for macOS
- Exit early if directories cannot be created
- Suggest adding `${LUCET_BIN_DIR}/devenv_setenv.sh` to the shell configuration, with different instructions for the `fish` shell
> Improve the install target

- lucet-analyze/src/main.rs
- lucet-module-data/src/globals.rs
- lucet-module-data/src/lib.rs
- lucet-runtime/lucet-runtime-internals/src/alloc/mod.rs
- lucet-runtime/lucet-runtime-internals/src/alloc/tests.rs
- lucet-runtime/lucet-runtime-internals/src/instance.rs
- lucet-runtime/lucet-runtime-internals/src/module/mock.rs
- lucet-runtime/lucet-runtime-internals/src/vmctx.rs
- lucet-runtime/lucet-runtime-tests/src/globals.rs
- lucetc/src/decls.rs
- lucetc/tests/wasi-sdk.rs
- lucetc/tests/wasm.rs
- lucetc/tests/wasm/globals_export.wat
Split from #196 into changes I'd be comfortable squashing together:
This adjusts globals to allow for a global exported by multiple names, and adds support for globals of type `f32` and `f64`. This is sufficient to get us spec-compliant for globals!
I noticed `lucet-analyze` was missing information about globals, so I added that as well.
This makes global values a union and adds some unsafe as a consequence, but my understanding is that type confusion of globals would requite wasm that doesn't validate, so this "only" would require additional unsafe code on the embedder's side. Since I imagine it's relatively unlikely to be prodding an instance's globals outside initialization, that seems acceptable vs the additional implementation complexity of separating out globals by type.
> Float global support

- lucetc/src/load.rs
When the input is neither valid WASM nor WAT, only print that rather than the wat2wasm error.
This prevents the terminal from exploding after pages of garbage (from a WAT parser perspective) are printed whenever one inadvertently types "lucetc-wasi" instead of "lucet-wasi".
> lucetc: do not print the full error returned by wat2wasm

- .travis.yml
- Dockerfile.toolchain
- Makefile
- devenv_build_container.sh
- devenv_build_toolchain_only.sh
- helpers/install.sh
This adds the ability to build a new Docker image, `lucet-toolchain`, that only contains the Lucet toolchain, and not the boilerplate to build it.
Lucet tools can then be directly used as:
```sh
docker run --rm lucet-toolchain lucet-wasi ...
```
This image is based on the current Ubuntu, and uses the stock LLVM installation, so it can be used as a base image for projects willing to build upon Lucet.
> Add support for small(er) Docker images to use (not work on) Lucet

- lucet-wasi/src/hostcalls/fs.rs
- lucet-wasi/src/hostcalls/misc.rs
- Remove unneeded `unsafe` blocks; codecs don't need these any longer.
- Removing a directory without `REMOVEDIR` may return `EPERM` instead of  `EISDIR`. Adjust accordingly. (thanks, @kubkon)
- If a path cannot be opened, set the file descriptor to `wasi_fd_t::max_value()`
This is fixing tests from https://github.com/sunfishcode/misc-tests
> WASI fixes

- lucet-runtime/include/lucet_types.h
Error::NoLinearMemory was added in d03aaad7b198ab4e4eff442e213871801df5c36f, but it didn't update the C header, causing GDB to display lucet_error incorrectly.
This change makes the definition of `lucet_error` in `lucet_types.h` same with `Error` in [error.rs](https://github.com/fastly/lucet/blob/master/lucet-runtime/lucet-runtime-internals/src/error.rs)
> lucet-runtime: add missing lucet_error_no_linear_memory in C header

- Cargo.lock
- lucet-runtime/lucet-runtime-tests/Cargo.toml
- lucet-runtime/lucet-runtime-tests/src/stack.rs
- lucetc/src/lib.rs
- lucetc/src/load.rs
This takes care of #193. :smile_cat: 
Adds a `from_bytes<B: AsRef<[u8]>>(bytes: B)` method so that `lucetc::Lucetc` can be constructed from bytes. This means that we aren't required to write a program to disk in certain situations, if we already have the wasm binary content in memory.
`from_bytes` is used rather than a `from_path` because I didn't want to change the behavior of `new`.
While poking around at this I found that the stack tests in `lucet-runtime/lucet-runtime-tests/src/stack` were a good candidate to switch from `Lucetc::new` to `Lucet::from_bytes`, skipping the need to write the wat content generated by `generate_test_wat` to a file in the tempdir. :tada: 
p.s. big thanks & kudos to @awortman-fastly for helping me out getting started w/ this :tada:
> lucetc::Lucetc::from_bytes

- benchmarks/shootout/Makefile
- lucetc/src/compiler.rs
`best` doesn't exist any more.
Fixes #216
> Update the shootout makefile to use the `fast` optimization level

- benchmarks/lucet-benchmarks/src/modules.rs
well. _add_ an entrypoint function signature. The code compiles but when running `lucet-benchmark`, specifically "run_many_args", it fails because the mock module has the default signature of `() -> ()` where we provide ~66 arguments.
> Fix benchmark entrypoint function signature

- lucet-wasi/src/host.rs
`st_*tim` value are in seconds, not nanoseconds.
> Fix nix->wasi file timestamp conversion

- Cargo.toml
- helpers/bump-global-version.sh
Check that in their current state, subpackages can be published.
Only then, set the global version number to the same as the main Cargo.toml file
Then, try one last dry run with the new version number.
> Add a helper script to set the global package version

- lucet-runtime/lucet-runtime-internals/src/val.rs
- lucet-runtime/tests/val.rs
This allows only creating it from values that can be fully safely represented.
The reason to do this is for writing tests in downstream crates that want to
test what is done with the result of a guest run.
Closes #211
> Allow creating UntypedRetVal

- lucet-idl/src/data_layout.rs
- lucet-idl/src/lib.rs
- lucet-idl/src/module.rs
- lucet-idl/src/package.rs
- lucet-idl/src/parser.rs
- lucet-idl/src/types.rs
- lucet-runtime/lucet-runtime-tests/src/strcmp.rs
The idea was we would use these to annotate datatypes with
backend-specific stuff, e.g. use this name for the struct in C and this name in Rust.
But we never ended up actually doing so. Defaults have worked fairly well so far.
When we end up needing annotations for specific nodes in the AST, we can go back
and add them just where they will be used.
> lucet-idl: delete attrs

- assemblyscript/examples/signatures/README.md
- assemblyscript/examples/signatures/assembly/index.ts
- assemblyscript/examples/signatures/assembly/wasm-crypto/__tests__/faRistrettoPoint.spec.ts
- assemblyscript/examples/signatures/assembly/wasm-crypto/__tests__/hash.spec.ts
- assemblyscript/examples/signatures/assembly/wasm-crypto/__tests__/utils.spec.ts
- assemblyscript/examples/signatures/assembly/wasm-crypto/crypto.ts
- assemblyscript/examples/signatures/package-lock.json
- assemblyscript/examples/signatures/package.json
- assemblyscript/modules/wasa/README.md
- assemblyscript/modules/wasa/assembly/index.ts
- assemblyscript/modules/wasa/assembly/wasa.ts
- assemblyscript/modules/wasa/bindings.json
- assemblyscript/modules/wasa/package.json
This is an update to the AssemblyScript module and example, after the new
runtimes landed into the AssemblyScript compiler.
WASA, the WASI bindings, got a major update, not only to support the new ASC,
but also to support most of WASI as it is today.
Breaking changes were made to the API to make is both safer and closer to the
NodeJS filesystem API.
wasm-crypto was updated for the new runtime as well.
The example was updated for the new runtime and the new WASA API.
The AssemblyScript compiler still has some rough edges regarding garbage
collection. So, switch the runtime from `full` (default) to `stub` for now,
until some known regressions have been ironed out.
> Update AssemblyScript, WASA and the AssemblyScript example and instructions

- lucet-analyze/src/main.rs
- lucet-module-data/src/lib.rs
- lucet-module-data/src/module.rs
- lucet-module-data/src/module_data.rs
- lucet-module-data/src/signature.rs
- lucet-module-data/src/tables.rs
- lucet-runtime/lucet-runtime-internals/src/module.rs
- lucet-runtime/lucet-runtime-internals/src/module/dl.rs
- lucetc/src/compiler.rs
- lucetc/src/decls.rs
- lucetc/src/function.rs
- lucetc/src/function_manifest.rs
- lucetc/src/output.rs
- lucetc/src/table.rs
This (finally!) makes a change we discussed a few months ago and has compilation produce binaries where all the internal components we need are reachable from a single symbol (`lucet_module`). This is nice for organization reasons, but generally reduces our dependence on `dlsym` as well as removing a few failure modes that were never realistically hit, like `function_manifest_len` not being present in a lucetc-compiled `.so`
Because other structures are internal and reachable via `lucet_module` and the `NativeData` it points to, most symbols are no longer exported.
> Reorganize lucet module binary format

- Cargo.lock
- lucet-builtins/wasmonkey/Cargo.toml
- lucet-builtins/wasmonkey/src/patcher.rs
We used to assume that there was always a name section.
But running `wasm-opt` can strip that section.
> wasmonkey: create a new name section if there isn't any

- Dockerfile
- Dockerfile.toolchain
- devenv_build_toolchain_only.sh
- helpers/install.sh
- lucet-wasi-sdk/src/lib.rs
- lucet-wasi/build.rs
tested with a local build of wasi-sdk 6.0. PR pending on https://github.com/CraneStation/wasi-sdk/pull/50 getting merged & tagged.
> upgrade wasi-sdk to 6.0, which uses llvm 8.0.1

- lucet-runtime/tests/instruction_counting/unreachable_call.wat
- lucetc/src/function.rs
`Call` and `CallIndirect` leave counting the corresponding `Return` to the caller, but we weren't checking if the caller was even reachable, so we would try to count even in unreachable calls.
This violated a [consistency check](https://github.com/fastly/lucet/blob/56396177cafe92ca945a0667bab0908672415e88/lucetc/src/function.rs#L236-L241) which caused failures in spec tests, and otherwise would have resulted in either incorrect overcounting or panicking in cranelift, so I'm pretty happy about having that assert now :)
> Do not try to count returns for unreachable calls as executed

- Cargo.lock
- lucet-module/Cargo.toml
- lucet-runtime/lucet-runtime-internals/Cargo.toml
- lucetc/Cargo.toml
Using an old version prevents applications using the `lucet` crate from also using `bincode` 1.1.
> Update the bincode crate to version 1.1

- .gitmodules
- Cargo.lock
- Cargo.toml
- lucet-module/Cargo.toml
- lucetc/Cargo.toml
which has a security-critical bugfix.
also brings in:
* latest cranelift master (0.41.0 plus the cranelift 0.11 patch, and some others, merged in)
* target-lexicon 0.8.0
* wasmparser 0.37.0
and deletes the faerie submodule. Using the submodule was valuable way back when faerie and the rest of the deps were changing pretty frequently, but its past being useful, we can stick to the crates.io releases from now on, or switch back to the submodule again if the need arises.
> upgrade to Faerie 0.11

- Dockerfile
building `cargo-audit`, `cargo-watch`, and `rsign2` in release for `cargo install` takes >50% of our build times. :crossed_fingers: that building in debug and eating the increased runtime is a net improvement, but we'll see.
> cargo install with debug to avoid full release build times

- Cargo.lock
- Cargo.toml
- lucet-idl/src/config.rs
- lucet-idl/src/error.rs
- lucet-idl/src/lib.rs
- lucet-idl/src/main.rs
- lucet-idl/tests/example.rs
- lucet-idl/tests/wasi_unstable.rs
- lucet-idl/witx-frontend/Cargo.toml
- lucet-idl/witx-frontend/src/ast.rs
- lucet-idl/witx-frontend/src/lexer.rs
- lucet-idl/witx-frontend/src/lib.rs
- lucet-idl/witx-frontend/src/main.rs
- lucet-idl/witx-frontend/src/parser.rs
- lucet-idl/witx-frontend/src/sexpr.rs
- lucet-idl/witx-frontend/src/toplevel.rs
- lucet-idl/witx-frontend/src/validate.rs
witx-frontend is going to get moved to the WASI repo. This separates it out from lucet-idl.
Once it is merged into the WASI repo, it will be deleted from this one.
At the moment, none of the generators in lucet-idl understand witx yet, so there's no need to even put a dependency on witx-frontend in that crate.
The test to parse wasi_unstable has been deleted, I'll have to recreate it with the right path in the wasi repo, and its otherwise trivial.
> split lucet-idl and witx-frontend into two separate crates

- lucet-analyze/src/main.rs
we were going through the mapper to read each table, but incorrectly
assumed the pointer in the artifact to look at didn't need translation
too
This fixes the issue @shravanrn hit in #300 and while this gets `lucet-analyze` happily reading modules with tables, it doesn't do so very nicely:
```
Tables:
Table 0: [TableElement { ty: 18446744073709551615, func: 0 }, TableElement { ty: 0, func: 1312 }, TableElement { ty: 0, func: 1328 }, TableElement { ty: 1, func: 1344 }]
```
> lucet-analyze: go through the ELF view to read the tables slice

- Cargo.lock
- benchmarks/lucet-benchmarks/src/compile.rs
- benchmarks/lucet-benchmarks/src/par.rs
- benchmarks/lucet-benchmarks/src/seq.rs
- lucet-module/Cargo.toml
- lucet-spectest/src/script.rs
- lucet-wasi-sdk/tests/lucetc.rs
- lucetc/Cargo.toml
- lucetc/src/compiler.rs
- lucetc/src/decls.rs
- lucetc/src/options.rs
- lucetc/tests/wasm.rs
Brings in Cranelift 0.44.0 and wasmparser 0.39.1.
* Wasmparser 0.39.1 returns much better errors on a verifier error
* Cranelift-wasm uses the latest wasmparser, and exposes custom sections to module environment (relevant to #152)
* lots of other cranelift codegen updates. the known regression in 0.43 is fixed in this release
> upgrade to cranelift 0.44.0, wasmparser 0.39.1

- lucet-runtime/lucet-runtime-internals/src/alloc/mod.rs
- lucet-runtime/lucet-runtime-internals/src/instance/signals.rs
- lucet-runtime/lucet-runtime-internals/src/region/mmap.rs
where it was protecting against stack underflow into globals, which are
extremely unlikely. Far more likely, are stack overflows into the
instance's heap, where we accidentally caught those via heap guard space
instead. If an instance's `Limits` had the number of heap guard pages as
0, which is permissible, an instance with full utilization would then
map a page that had been acting as a stack guard page as read/write and
remove the guard-ness of that page.
This commit moves a page to be an outside-of-heap dedicated stack guard
page.
> Move the stack guard page between the stack and heap

- benchmarks/lucet-benchmarks/src/context.rs
- lucet-runtime/lucet-runtime-internals/src/context/mod.rs
`pthread_sigmask` is the safe choice for a multithreaded environment. Per `sigprocmask(2)`:
> The use of sigprocmask() is unspecified in a multithreaded process; see pthread_sigmask(3).
> Switch uses of sigprocmask to pthread_sigmask

- lucet-wasi/tests/guests/poll.c
- lucet-wasi/tests/test_helpers/mod.rs
- lucet-wasi/tests/tests.rs
- Removes a `sleep` that wasn't relevant for testing `poll`
- Timeout step waits on an in-process pipe rather than stdin, which should make its behavior more consistent across environments
- Temporarily ignores the test while we debug its behavior in certain CI environments
The commit log for this is a bit messy, so I'm planning to squash it when merging.
> Make WASI `poll` test more deterministic, but disable pending debugging

- lucet-validate/tests/wasitests.rs
Ephemeral files left around by editors were causing a panic.
> Ignore non-c/wat files in lucet-validate test rather than failing

- Cargo.lock
- Cargo.toml
- benchmarks/lucet-benchmarks/Cargo.toml
- helpers/bump-global-version.sh
- lucet-idl/Cargo.toml
- lucet-module/Cargo.toml
- lucet-objdump/Cargo.toml
- lucet-runtime/Cargo.toml
- lucet-runtime/lucet-runtime-internals/Cargo.toml
- lucet-runtime/lucet-runtime-tests/Cargo.toml
- lucet-spectest/Cargo.toml
- lucet-validate/Cargo.toml
- lucet-wasi-fuzz/Cargo.toml
- lucet-wasi-sdk/Cargo.toml
- lucet-wasi/Cargo.toml
- lucetc/Cargo.toml
Doing the PR first, then I'll tag `0.2.0` once it's :heavy_check_mark:
Fun fact, because `lucet-module-data` is now `lucet-module` none of the `cargo publish --dry-run` work!
> Bump Lucet crate versions to 0.2.0

- lucetc/src/options.rs
`lucetc` usage indicates `none`, `speed` and `speed_and_size` as optimization levels, but these are rejected.
```sh
$ lucetc --opt-level none a.c
thread 'main' panicked at 'unknown value for opt-level', lucetc/src/options.rs:116:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
This fixes it.
> lucetc 0.2.0: fix --opt-level {none, speed, speed_and_size}

- lucet-module/src/version_info.rs
- lucet-module/tests/version.rs
- lucet-runtime/lucet-runtime-internals/src/module/dl.rs
Motivated by https://github.com/fastly/ExecuteD/pull/9#issuecomment-541101657, when the runtime doesn't have a commit hash in its version info, but the lucetc does, we were rejecting modules simply for having a too specific version.
> More permissive module version check

- Cargo.lock
- Cargo.toml
- benchmarks/lucet-benchmarks/Cargo.toml
- lucet-module/Cargo.toml
- lucet-objdump/Cargo.toml
- lucet-runtime/Cargo.toml
- lucet-runtime/lucet-runtime-internals/Cargo.toml
- lucet-runtime/lucet-runtime-tests/Cargo.toml
- lucet-spectest/Cargo.toml
- lucet-validate/Cargo.toml
- lucet-wasi-fuzz/Cargo.toml
- lucet-wasi-sdk/Cargo.toml
- lucet-wasi/Cargo.toml
- lucetc/Cargo.toml
This is the last of the packaging stuff for now, and some point later we can look at fixing cyclic dev-dependencies. This would include #333 and #328 in 0.2.0 -> 0.2.1, which seems appropriate for a patch bump.
> Bump lucet crates to 0.2.1

- Cargo.lock
- lucetc/Cargo.toml
- lucetc/src/load.rs
- lucetc/src/main.rs
Currently, given malformed wasm text like
```
(module
(type (func (param i32 i32 i32 i32) (result i32)))
(func $write (import "wasi_unstable" "fd_write") (type 0)) 
(func $strlen (param i32) (result i32)
(local i32 i32 i32)
locaf l.get 0   ;; <----- this is the important line. "locaf" is very much not a wasm opcode!
local.set 1
local.get 1
local.get 0
i32.sub)
(memory (;0;) 2)
(export "memory" (memory 0)) 
(data (i32.const 0) "0123456789\00a\00\00\00\00")
(data (i32.const 16) "strlen(\"a\") is: \00\n")
;; iovec struct for eventually printing "strlen("a") is: ""
(data (i32.const 64) "\10\00\00\00\12\00\00\00")
(func $_start (export "_start")
i32.const 32
(call $strlen (i32.const 11))
;; fix up line to print by loading the digit at result of strlen (should be in [0,9])
i32.load8_u …
```
> Improve lucetc error messages

- Cargo.lock
- lucetc/Cargo.toml
- lucetc/src/main.rs
- lucetc/src/options.rs
This is meant to be a starting point for more semantic error reporting, but in order to get there we'll need to do a broader refactor of our error types.
Example use and output:
```
acfoltzer@stribog:~/src/isolation/public/lucetc % cargo run -p lucetc -- sdflkj
Finished dev [unoptimized + debuginfo] target(s) in 0.08s
Running `/home/acfoltzer/src/isolation/public/target/debug/lucetc sdflkj`
Error: No such file or directory (os error 2)
acfoltzer@stribog:~/src/isolation/public/lucetc % cargo run -p lucetc -- sdflkj --error-style json
Finished dev [unoptimized + debuginfo] target(s) in 0.09s
Running `/home/acfoltzer/src/isolation/public/target/debug/lucetc sdflkj --error-style json`
{"error":"No such file or directory (os error 2)"}
```
In `--error-style json` mode, the error is a single …
> Add very basic JSON formatting for lucetc errors

- lucet-runtime/lucet-runtime-internals/src/embed_ctx.rs
- lucet-runtime/lucet-runtime-internals/src/instance.rs
- The `Send + Sync` restriction on the downcast methods was leftover from before the `State` refactor lifted those restrictions from `YieldedVal`s
- The mutable borrow on `Instance::get_embed_ctx_mut()` is checked at runtime by the `RefCell`s inside the underlying map. This patch gives us fewer compile-time guarantees, but holding a mutable borrow on the entire instance just to get at an embedding context is way too strict
> [lucet-runtime] relax unnecessary restrictions on some functions

- lucet-runtime/lucet-runtime-internals/src/context/context_asm.S
- lucet-runtime/lucet-runtime-internals/src/context/mod.rs
- lucet-runtime/lucet-runtime-internals/src/instance/execution.rs
By being `#[no_mangle]` this causes unnecessary symbol conflicts in the presence of other `lucet-runtime-internals`es.
> Allow KillState's `exit_guest_region` to be name-mangled

- Cargo.lock
- Cargo.toml
- benchmarks/lucet-benchmarks/Cargo.toml
- lucet-module/Cargo.toml
- lucet-objdump/Cargo.toml
- lucet-runtime/Cargo.toml
- lucet-runtime/lucet-runtime-internals/Cargo.toml
- lucet-runtime/lucet-runtime-tests/Cargo.toml
- lucet-spectest/Cargo.toml
- lucet-spectest/src/lib.rs
- lucet-validate/Cargo.toml
- lucet-wasi-fuzz/Cargo.toml
- lucet-wasi-sdk/Cargo.toml
- lucet-wasi/Cargo.toml
- lucetc/Cargo.toml
Only a few changes since 0.2.1:
* lucetc error messages include the underlying error from wabt
* lucet-runtime supports timeouts
* lucetc can emit errors as json
* lucet-runtime removes unnecessary restrictions on some functions
> Bump versions to 0.3.0

- lucet-runtime/lucet-runtime-internals/src/instance.rs
- lucet-runtime/lucet-runtime-internals/src/instance/state.rs
- lucetc/src/main.rs
- We don't have the capability to produce multiple errors yet, so this only returns an array of a single element. Returning multiple errors will require refactoring of our code as well as upstream dependencies.
- Previously a client would have to keep around the `RunResult` to know which state an instance is in.
> Report Lucetc JSON errors as an array; add state accessors to Instances

- Cargo.lock
- Cargo.toml
- benchmarks/lucet-benchmarks/Cargo.toml
- lucet-module/Cargo.toml
- lucet-objdump/Cargo.toml
- lucet-runtime/Cargo.toml
- lucet-runtime/lucet-runtime-internals/Cargo.toml
- lucet-runtime/lucet-runtime-tests/Cargo.toml
- lucet-spectest/Cargo.toml
- lucet-validate/Cargo.toml
- lucet-wasi-fuzz/Cargo.toml
- lucet-wasi-sdk/Cargo.toml
- lucet-wasi/Cargo.toml
- lucetc/Cargo.toml
Keeping this as a minor semver change because API changes were restricted to `lucet-runtime-internals` functions that are not exported via `lucet-runtime`.
> Bump crate versions to 0.3.1

- .github/workflows/fuzz.yml
- Makefile
Run 100k fuzz tests per run of the fuzz job.
Github apparently gives us six hours per job, so we can probably turn this up once we know how long that number takes on their infra.
> Run more test cases per fuzz job

- Cargo.lock
- Makefile
- lucet-module/src/lib.rs
- lucet-module/src/module_data.rs
- lucet-runtime/lucet-runtime-internals/Cargo.toml
- lucet-runtime/lucet-runtime-internals/src/module/dl.rs
- lucet-runtime/lucet-runtime-internals/src/module/mock.rs
- lucet-spectest/src/script.rs
- lucetc/Cargo.toml
- lucetc/src/compiler.rs
- lucetc/src/compiler/cpu_features.rs
- lucetc/src/decls.rs
In theory if a module is built with features the runtime doesn't support, the runtime will fail to load the module with a descriptive error.
"In theory" because I don't have a test for this, although it seems correct - I could be convinced to add a test-only feature in lucetc so we can write a test around missing features being rejected, but because each feature is hand-specified, even that's a little brittle. Comments and opinions encouraged, as it's very much not my favorite code.
Also fixes lucet-spectest bitrot and adds a build of it to `make test`.
> Include CPU features in module data

- lucet-wasi/src/main.rs
fixes https://github.com/fastly/lucet/issues/360 where the runtime's C
API was being discarded by the linker.
This load-bearing no-op was removed in https://github.com/fastly/lucet/commit/42f6015b3aa72f28178308160aabf8f13757eb05#diff-73b027b3e246720be89ae930ae180a18L42, which looks accidental in moving around wasi exports?
> replace lucet_runtime ensure_linked in lucet-wasi

- lucet-runtime/src/lib.rs
found a small typo while reading through `lucet-runtime` docs. this patches it :slightly_smiling_face:
> minor grammar fix in runtime docs

- Cargo.lock
- Cargo.toml
- benchmarks/lucet-benchmarks/src/modules.rs
- lucet-module/Cargo.toml
- lucet-objdump/Cargo.toml
- lucet-runtime/Cargo.toml
- lucet-runtime/lucet-runtime-internals/Cargo.toml
- lucet-runtime/lucet-runtime-internals/src/hostcall_macros.rs
- lucet-runtime/lucet-runtime-internals/src/lib.rs
- lucet-runtime/lucet-runtime-internals/src/vmctx.rs
- lucet-runtime/lucet-runtime-macros/Cargo.toml
- lucet-runtime/lucet-runtime-macros/src/lib.rs
- lucet-runtime/lucet-runtime-tests/Cargo.toml
- lucet-runtime/lucet-runtime-tests/src/entrypoint.rs
- lucet-runtime/lucet-runtime-tests/src/guest_fault.rs
- lucet-runtime/lucet-runtime-tests/src/host.rs
- lucet-runtime/lucet-runtime-tests/src/strcmp.rs
- lucet-runtime/lucet-runtime-tests/src/timeout.rs
- lucet-runtime/src/c_api.rs
- lucet-runtime/src/lib.rs
- lucet-spectest/Cargo.toml
- lucet-spectest/src/bindings.rs
- lucet-validate/Cargo.toml
- lucet-wasi-fuzz/Cargo.toml
- lucet-wasi-sdk/Cargo.toml
- lucet-wasi/Cargo.toml
- lucet-wasi/src/wasi.rs
- lucetc/Cargo.toml
The attribute macro is much more flexible syntactically, and in particular allows hostcall implementations to be properly `rustfmt`ed rather than being stuck in the invocation of a macro.
This PR also bumps the version to 0.4.2 due to a new API and a deprecation.
Unfortunately the size of the diff is pretty large on this patch, but it's mostly due to the indentation changes that are necessary when converting from a macro invocation block to an attribute.
> Add `#[lucet_hostcall]` attribute macro and deprecate `lucet_hostcalls!`

- .github/actions/test/action.yml
- .github/workflows/main.yml
- Cargo.lock
- Dockerfile
- Makefile
- benchmarks/lucet-benchmarks/src/seq.rs
- lucet-module/Cargo.toml
- lucet-validate/Cargo.toml
- lucet-validate/src/lib.rs
- lucet-validate/tests/wasitests.rs
- lucet-wasi-fuzz/src/main.rs
- lucet-wasi-sdk/tests/lucetc.rs
- lucet-wasi/Cargo.toml
- lucet-wasi/src/c_api.rs
- lucet-wasi/src/main.rs
- lucet-wasi/tests/test_helpers/mod.rs
- lucet-wasi/tests/tests.rs
- lucetc/Cargo.toml
* pull in latest Cranelift release 0.51
* upgrade to wasi-common 0.7, which fixes a lot of the WasiCtxBuilder
stuff that required many extra unwraps
* pull in latest WASI repo. This moves the preview0 stuff to another
directory. Biggest change here is that the lucetc deb, which includes
the wasi witx files, has a slightly different file layout now.
* transitive upgrades to target-lexicon, faerie
> upgrade cranelift, wasi-common, witx deps, and friends

- .github/workflows/fuzz.yml
- .github/workflows/main.yml
This commit fixes the CI by setting `actions/checkout` at version `v1`. The current master of `actions/checkout` now obsoleted the `with: submodules: true` input. See [actions/checkout/releases/tag/v2-beta] for more info.
[actions/checkout/releases/tag/v2-beta]: https://github.com/actions/checkout/releases/tag/v2-beta
> Use actions/checkout@v1 to support submodules checkout

- lucet-runtime/lucet-runtime-internals/src/instance.rs
I spent a little time last night getting a lay of the land in our spectests, seeing where things were failing. One of the small things I noticed related to global imports, and `Unsupported` error variant that is thrown by :point_down: this block in `lucet-runtime/lucet-runtime-internals/src/instance.rs:549`.
```rust
for (i, v) in mod_globals.iter().enumerate() {
globals[i] = match v.global() {
Global::Import { .. } => {
return Err(Error::Unsupported(format!(
"global imports are unsupported; found: {:?}",
i
)));
}
Global::Def(def) => def.init_val(),
};
}
```
This is passing the `usize` (functionally the import index here?) given by `enumerate` to the error. This
meant the error reported looked like this:
```
FAIL in Module, line 108: SpecTestError { inner: …
```
> Show unsupported global import in error message

- Cargo.lock
- lucet-module/Cargo.toml
- lucet-objdump/Cargo.toml
- lucet-runtime/Cargo.toml
- lucet-runtime/lucet-runtime-internals/Cargo.toml
- lucet-runtime/lucet-runtime-internals/src/hostcall_macros.rs
- lucet-runtime/lucet-runtime-internals/src/vmctx.rs
- lucet-runtime/lucet-runtime-macros/Cargo.toml
- lucet-runtime/lucet-runtime-tests/Cargo.toml
- lucet-spectest/Cargo.toml
- lucet-validate/Cargo.toml
- lucet-wasi-fuzz/Cargo.toml
- lucet-wasi-sdk/Cargo.toml
- lucet-wasi/Cargo.toml
- lucetc/Cargo.toml
This prevents resources like embedder contexts or heap views from living across yield points, which is important for safety since the host can modify the data underlying those resources while the instance is suspended.
Since this is a semver breaking change, this patch also updates the package versions.
> Make yield methods take `&mut Vmctx`; update semver

- .rustfmt.toml
This adds a blank `.rustfmt.toml` file, which ostensibly "tells tools we use `rustfmt`". While I can't actually find any example of a tool that falls over without a blank file in place, I figure this is still a nice-to-have for **(a)** the sake of explicitly stating that we are using the default formatting configuration, and **(b)** consistency with [cranelift](https://github.com/bytecodealliance/cranelift/blob/master/.rustfmt.toml) and [wasmtime](https://github.com/bytecodealliance/wasmtime/blob/master/.rustfmt.toml).
> add blank rustfmt config file

- lucet-runtime/lucet-runtime-internals/src/region/mmap.rs
This was previously accepted by the compiler but is being phased out;
It will become a hard error in a future `rustc` release.
See https://github.com/rust-lang/rust/issues/66145
> into_iter() -> iter() for arrays

- lucetc/src/decls.rs
For reasons unrelated to this PR, I ended up looking through `lucetc/src/decls.rs` this morning. I noticed a few warts that would be easy fixes, so this is a small gardening PR.
* Addresses two lint warnings about redundant field names, using the shorthand notation instead.
* Moves `*_name_for` helper functions nested inside of `declare_funcs` out of a loop body. This is just a small readability fix for our loop.
> ModuleDecls Cleanup

- Cargo.lock
- lucet-runtime/Cargo.toml
- lucet-runtime/lucet-runtime-internals/Cargo.toml
- lucet-runtime/lucet-runtime-internals/src/error.rs
- lucet-runtime/tests/instruction_counting.rs
In code review I wanted to understand exactly why lucetc was a dep of runtime-internals and by the time I used the compiler to figure it out, the fix was only two more lines.
> break lucetc dep in runtime-internals

- lucet-runtime/lucet-runtime-internals/src/instance/execution.rs
- lucet-runtime/src/lib.rs
It was already possible to use via the `Instance::kill_switch()` method, but couldn't be named in a type signature or a type declaration.
> Export the `KillSwitch` type from the public runtime API

- lucet-runtime/lucet-runtime-internals/src/embed_ctx.rs
- lucet-runtime/lucet-runtime-internals/src/region/mod.rs
This is another "tiny lint fix I found while looking around at things" PR.
Rather than using a `CtxMap::new()` constructor, we can implement the `Default` trait, and use that instead.
> replace empty constructor w/ default impl

- lucet-objdump/Cargo.toml
- lucet-runtime/Cargo.toml
- lucet-runtime/lucet-runtime-internals/Cargo.toml
- lucet-runtime/lucet-runtime-tests/Cargo.toml
- lucet-spectest/Cargo.toml
- lucet-validate/Cargo.toml
- lucet-wasi-sdk/Cargo.toml
- lucet-wasi/Cargo.toml
- lucetc/Cargo.toml
Most of our thinking about semver for this project is concerned with the more "public-facing" crates like `lucetc`, `lucet-runtime`, and `lucet-wasi`, as opposed to "implementation detail" crates like `lucet-module`, `lucet-runtime-internals`, etc. As the project matures, we are paying more attention to semver for all of the crates, but this change makes the released sets of packages more consistent.
> Use exact dependencies for crates within the repo

- Cargo.lock
- benchmarks/lucet-benchmarks/Cargo.toml
- lucet-module/Cargo.toml
- lucet-objdump/Cargo.toml
- lucet-runtime/Cargo.toml
- lucet-runtime/include/lucet_types.h
- lucet-runtime/lucet-runtime-internals/Cargo.toml
- lucet-runtime/lucet-runtime-internals/src/alloc/mod.rs
- lucet-runtime/lucet-runtime-internals/src/alloc/tests.rs
- lucet-runtime/lucet-runtime-internals/src/c_api.rs
- lucet-runtime/lucet-runtime-internals/src/instance/signals.rs
- lucet-runtime/lucet-runtime-internals/src/region/mmap.rs
- lucet-runtime/lucet-runtime-macros/Cargo.toml
- lucet-runtime/lucet-runtime-tests/Cargo.toml
- lucet-runtime/lucet-runtime-tests/src/guest_fault.rs
- lucet-runtime/lucet-runtime-tests/src/timeout.rs
- lucet-runtime/tests/c_api.c
- lucet-spectest/Cargo.toml
- lucet-validate/Cargo.toml
- lucet-wasi-fuzz/Cargo.toml
- lucet-wasi-sdk/Cargo.toml
- lucet-wasi/Cargo.toml
- lucet-wasi/src/main.rs
- lucetc/Cargo.toml
Most of this patch is actually to fix up the tests that were erroneously succeeding because of this bug. The core of the fix is here in `mmap.rs`:
```
-        let sigstack = globals + host_page_size();
+        let sigstack = globals + region.limits.globals_size + host_page_size();
```
This was causing the signal stack to begin one page after the start of the globals section, regardless of how big the globals are. This mostly wasn't causing problems because the default globals size is a page, and we _were_ still adding in a page for the guard, meaning the segments didn't actually overlap with default `Limits`. However, the guard page for the signal stack was missing, and configurations with larger globals sizes could end up overlapping the signal stack, potentially allowing guests to …
> Fix incorrect globals/sigstack allocation layout

- Cargo.lock
- benchmarks/lucet-benchmarks/Cargo.toml
- lucet-module/Cargo.toml
- lucet-objdump/Cargo.toml
- lucet-runtime/Cargo.toml
- lucet-runtime/lucet-runtime-internals/Cargo.toml
- lucet-runtime/lucet-runtime-macros/Cargo.toml
- lucet-runtime/lucet-runtime-tests/Cargo.toml
- lucet-spectest/Cargo.toml
- lucet-validate/Cargo.toml
- lucet-wasi-fuzz/Cargo.toml
- lucet-wasi-sdk/Cargo.toml
- lucet-wasi/Cargo.toml
- lucetc/Cargo.toml
This is a new thing we're trying in order to avoid phantom release numbers from appearing in the repo history.
In the past, we would bump the version when landing a PR according to semver rules.  This led to a situation where we had version `0.4.2` throughout the repo for some time without cutting a release, before landing a bigger PR that required a change to `0.5.0`. So, when we needed to increase the patch version for the `0.4.x` series, we ended up skipping `0.4.2` since it had existed for a time elsewhere in the history.
The hope is that if a similar situation arises today, the only versions that would have existed in the repo without being released are suffixed with `-dev`, avoiding this potential confusion.
> Bump version to `0.5.2-dev`

- lucet-spectest/src/script.rs
- lucet-wasi-sdk/tests/lucetc.rs
- lucetc/src/compiler.rs
- lucetc/src/lib.rs
- lucetc/tests/wasm.rs
I'd like to be able to run Lucet deterministically across machines and to do this I need canonicalized NaNs. I couldn't see a good existing data structure that was an argument for this constructor that this would slot in to, but I'm very open to suggestions! 9 arguments might be too many.
> Added a flag to canonicalize_nans

- CHANGELOG.md
- lucet-runtime/lucet-runtime-internals/src/alloc/tests.rs
- lucet-runtime/lucet-runtime-internals/src/region.rs
- lucet-runtime/lucet-runtime-internals/src/region/mmap.rs
These are not a substitute for checking for not-enough-slots errors when instantiating, but can be useful hints to embedders managing multiple regions.
> Add methods to get the number of used/free slots from a region

- lucet-validate/src/main.rs
- lucetc/src/error.rs
The full fix for these issues is tracked in #409, but this can merge first because it is already useful.
> Make lucetc and lucet-validate errors more verbose

- lucetc/src/lib.rs
Lucetc uses `target-lexicon` crate to detect the host OS.
On modern Macs, `target-lexicon` reports that the host is `Darwin`,
not `MacOSX`, at least I see this on my MacBook Pro running Catalina 10.15.2.
This leads to lucetc is not being able to set `LDFLAGS` correctly.
This change solves the issue by using the same LDFLAGS on both `Darwin` and `MacOSX`.
> Lucetc: fix macOS detection

- lucetc/src/lib.rs
It's often more convenient to let the compiler figure out how to invoke
the linker, but setting `env LD="$CC" ... lucetc ...` poses a problem:
`$CC` can often be `"$COMPILER --option1 --option2 ..."`, e.g. `clang
--target=$TARGET`, and the current code assumes that `LD` is a single
string specifying a program, rather than some string specifying a
program along with options.
While you could require that `LD` be strictly limited to a single
string, it seems more flexible and more in line with other build systems
to interpret `LD` as space-separated tokens, the first of which
specifies the program to invoke, and the remaining tokens specifying
arguments to be passed.
> be lenient in interpreting LD

- lucet-module/src/module_data.rs
- lucet-runtime/lucet-runtime-internals/src/instance.rs
- lucet-runtime/lucet-runtime-internals/src/module.rs
- lucet-runtime/lucet-runtime-internals/src/module/dl.rs
- lucet-runtime/lucet-runtime-internals/src/module/mock.rs
- lucet-runtime/tests/instruction_counting.rs
- lucetc/src/compiler.rs
This PR uses the `--count-instructions` option to set a new field in ModuleFeatures called `icnt`.  
**Notes:**
Leveraging the new field, the lucet-runtime call `get_instruction_count()` now returns an Option<u64>.  If the module was compiled with `--count-instructions`, the function returns the instruction count.  Otherwise, it returns None.
An extended set of tests affirm that get_instruction_count() appropriately returns Some(_) or None.
**See original issue at:**
https://github.com/bytecodealliance/lucet/issues/417
Fixes #417
> Issue #417: Retain whether or not a module was compiled with --count-instructions.

- lucetc/src/lib.rs
https://github.com/bytecodealliance/lucet/pull/405 introduced a new option to support NaNs canonicalization in the compiler.
Unfortunately, `LucetcOpts` was not updated properly to support the new flag in the public API. This change fixes that issue.
> Extend LucetOpt to support canonicalize_nans flag

- lucetc/src/compiler.rs
- lucetc/src/output.rs
- lucetc/src/table.rs
The table manifest was already being defined in the compiler, but the
relocation for the pointer to the guest tables was not, requiring a
fixup after the fact.  There's no need to do the fixup; we can define
the appropriate relocation while we're building all the tables.
> move table manifest relocations into the compiler

- lucet-runtime/lucet-runtime-internals/src/module/dl.rs
Some AMD CPUs fail on querying CPUID extended flags. See https://bugzilla.mozilla.org/show_bug.cgi?id=1615786. Performing this check only when actually required, allows wasm modules that don't rely on extended features to be run.
> Check extended CPU features only when necessary as querying flags fail on some AMD CPUs.

- lucet-runtime/lucet-runtime-internals/src/instance/execution.rs
The comment above our empty loop explains why this is in fact a valid and reasoned thing to do.
["_they're good loops, Brent!_"](https://cdn.vox-cdn.com/thumbor/O0nPoKhrAvL3YSV_Vu_VgLShESM=/1400x0/filters:no_upscale()/cdn.vox-cdn.com/uploads/chorus_asset/file/11732213/Screen_Shot_2018_07_23_at_2.15.34_PM.png)
> Allow empty loop in `exit_guest_region`

- lucet-runtime/lucet-runtime-internals/src/context/context_asm.S
:woman_farmer: :potable_water: :seedling: :corn: :sparkles: 
`lucet-runtime/lucet-runtime-internals/src/context/context_asm.S` has some inconsistent whitespace, and comment styles that was upsetting my editor. This is a gardening commit, since we're already looking at it over in #429.
> lucet-runtime-internals: fix whitespace, and `junk` comment warnings

- docs/src/Compiling-on-Linux.md
Was following these docs, and the URL redirects quite a bit (as the project moved under the Wasm org, and then points to an asset). Thus, Curl needs to follow these redirects to get the final asset :smile:
> Have curl follow redirects in compiling on linux docs

- lucetc/src/function.rs
We can avoid a second hashtable lookup by using a slightly different
`HashMap` API and working to satisfy the borrow checker.
> make FunctionInfo::get_runtime_func slight more efficient

- lucetc/src/compiler.rs
After bytecodealliance/cranelift#1209, the semantics of
`DataContext::define_zeroinit` appear to only be for truly
zero-initialized data that won't have any relocations applied to it.
Since `guest_start` is clearly not that kind of data, move to using
`DataContext::define` instead.
> lucetc: don't use define_zeroinit for guest_start data

- Cargo.lock
- lucet-validate/Cargo.toml
- lucet-validate/src/lib.rs
- lucet-validate/src/main.rs
- lucet-validate/tests/wasitests.rs
- lucet-wasi-sdk/tests/lucetc.rs
- lucetc/lucetc/main.rs
and bump the wasi repo to the very latest, so we have up-to-date spec files as well.
> update lucet-validate to support multiple witx files, use witx 0.8.3

- CHANGELOG.md
- Cargo.lock
- benchmarks/lucet-benchmarks/Cargo.toml
- benchmarks/lucet-benchmarks/src/par.rs
- lucet-runtime/lucet-runtime-internals/Cargo.toml
- lucet-runtime/lucet-runtime-internals/src/alloc/mod.rs
- lucet-runtime/lucet-runtime-internals/src/alloc/tests.rs
- lucet-runtime/lucet-runtime-internals/src/instance.rs
- lucet-runtime/lucet-runtime-internals/src/instance/signals.rs
- lucet-runtime/lucet-runtime-tests/src/guest_fault.rs
- lucet-runtime/src/lib.rs
These new APIs allow advanced use cases to control the installation and removal of the signal handler and alternate signal stack manually. This can be useful for reducing the number of synchronization points and syscalls required when running an instance.
Adds some tests to everyone's favorite `guest_fault` to make sure signals can in fact still be handled under these manual regimes, and adds some variants to the parallel benchmarks to show that manual control does in fact speed things up ever so slightly.
This partially addresses #281, since `Instance::run()` is faster when this automation is disabled.
> Add APIs to optionally disable automatic signal handler and sigstack installation

- Cargo.lock
- lucet-module/Cargo.toml
- lucet-validate/Cargo.toml
- lucet-wasi-sdk/Cargo.toml
- lucetc/Cargo.toml
- lucetc/src/error.rs
- lucetc/src/output.rs
Good news! `failure` is no longer used in Lucet. Most of this work was done by @froydnj in #447 .
This PR cleans up one straggler dependency in wasi-sdk that isnt needed, and points at some upstream improvements to `faerie` and `cranelift-module`'s error messages.
Along with that, we point wasmtime at the just-released `cranelift-v0.60.0` tag.
> upgrade to cranelift 0.60.0, lucetc error reporting fixes

- lucetc/src/compiler.rs
- lucetc/src/output.rs
- lucetc/src/stack_probe.rs
- lucetc/src/table.rs
This doesn't completely move to using `object`, but it seems like a good stopping point for discussion.
The only real ugliness is the `traps_to_module_traps`/`write_trap_table` division.  Ideally, these would be a single function, but the borrow checker says that the `ModuleCompiledFunction` that comes out of `Module::define_function` represents a borrow on the `Module` itself, so you can't have a single function that takes `&mut Module` and `&ModuleCompiledFunction`.  (`ModuleCompiledFunction` isn't actually exported, either, which seems like an oversight.) Ergo, we have to do a dance to satisfy the borrow checker.  Maybe it would have been a good idea to just make `Module::define_function` take a trap sink instead of trying to have `cranelift-module` backends manage the traps …
> move to using cranelift-module to emit structures rather than faerie

- .github/workflows/fuzz.yml.disabled
- .github/workflows/mac-ci.yml.disabled
- .github/workflows/main.yml
- Cargo.lock
- Cargo.toml
- lucet-validate/Cargo.toml
- lucet-wiggle/Cargo.toml
- lucet-wiggle/generate/Cargo.toml
- lucet-wiggle/runtime/Cargo.toml
Currently, our checked-in `Cargo.lock` is the only thing saving us from a dependency clash due to multiple `witx`es being compiled into `lucet-wiggle-generate`. This addresses that by making sure that all `witx`es in the dependency forest point to the `witx` in the `wasmtime` submodule.
This started as a cherry-pick of fd8a6237c0f02bf6548d8f1b724ccb6eaa5ef3e6, but I had to tweak things to work with the previously-used revision of `wasmtime`. Newer Cranelift revisions are not as readily compatible with `lucetc`, and this needed a quick fix.
> Use wasmtime submodule to satisfy witx and wiggle dependencies

- Cargo.lock
- lucet-validate/Cargo.toml
- lucet-wiggle/Cargo.toml
- lucet-wiggle/generate/Cargo.toml
- lucet-wiggle/tests/wasi.rs
- lucetc/src/compiler.rs
- lucetc/tests/wasm.rs
Conflicting versions of witx has broken master :(. This PR should resolve all of those issues, unblocking #460 
Pointing at latest wasmtime module introduces some minor incompatibilities with lucetc and lucet-wiggle.
* Change lucetc to pass our own TrapSink to cranelift-module for codegen
* Fix the lucet-wiggle tests for an update to wiggle
> Point at latest wasmtime master; fix witx crate resolution and update lucetc

- lucetc/src/error.rs
- lucetc/src/table.rs
- lucetc/tests/wasm.rs
- lucetc/tests/wasm/element_out_of_range.wat
Key phrase from the [spec][spec]:
> The `min` size in the limits of the table type specifies the initial size of that table, while its `max`, if present, restricts the size to which it can grow later.
In other words, at compile time the largest a table is allowed to be is its `min` limit. The `max` limit, if present, only limits the size to which the table can grow via `table.grow` instructions at runtime.
Previously, if we found an element section that specified an index offset past the end of the table vector, we would obligingly grow it longer, even if it exceeded the `min` limit of the table (and possibly the `max` value as well?). This patch changes the behavior to allocate a vector of `min` length and return an error if any element initializers would overflow it.
There's a new test …
> 🔧 limit compile-time table elements to the table's min

- Makefile
- helpers/lucet-toolchain-tests/objdump.sh
- lucetc/src/table.rs
A little while ago one of the changes to `lucetc` resulted in the field for "number of tables" instead holding "number of entries in the first table, or zero". This would be a bigger issue* if wasm ever used tables other than 0, but it doesn't for the time being, so the next likely place to run afoul of this is in `lucet-objdump` which crashes trying to read more tables than there really are, following stray pointers.
This change switches back to reporting the number of tables as the [length of the list of tables](https://github.com/bytecodealliance/lucet/blob/master/lucet-module/src/module.rs#L27), and includes a smoke-test through `lucet-objdump` to catch issues like this in the future.
* a longer description of why this isn't a severe issue for `lucet-runtime`: either there are zero …
> Fix lucetc reporting the number of tables incorrectly

- lucet-module/src/linear_memory.rs
Following up from a recent conversation in https://github.com/bytecodealliance/lucet/pull/466.
> Delete incorrect assumption about the max_size in a HeapSpec.

- .github/ISSUE_TEMPLATE/blank-issue.md
This creates a basic "Blank Issue" [Github issue template](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository) along the lines of the one [used by wasmtime](https://github.com/bytecodealliance/wasmtime/issues/new/choose). My primary motivation for this initial change is to prompt an alternative of private reporting of security issues, but over time we could add more templates that will help structure general reports.
> Add blank Github issue template

- lucet-runtime/lucet-runtime-internals/src/context/context_asm.S
- lucet-runtime/lucet-runtime-internals/src/context/mod.rs
- lucet-runtime/lucet-runtime-internals/src/instance.rs
- lucet-runtime/lucet-runtime-internals/src/instance/execution.rs
- lucet-runtime/lucet-runtime-internals/src/instance/signals.rs
- lucet-runtime/lucet-runtime-tests/src/timeout.rs
This updates the `lucet_runtime_internals::instance::execution` module so that `KillSwitch::terminate` will also terminate pending instances.
_Before_ if an instance was remotely terminated _before_ running, the result would be a `KillError::NotTerminable` error. Moreover, the instance would still run a guest context if `run` was called afterwards.
_Now_ if an instance is remotely terminated _before_ running, the result will now be `Ok(KillSuccess::Cancelled)` rather than a `KillError::NotTerminable` error. The instance will then enter a `Domain::Cancelled` state, and will not enter a guest region when `run` is called.
This is best summarized in a small snippet, assuming an initialized instance `inst`:
```rust
let inst: Instance = // ...
let kill_switch = inst.kill_switch(); …
```
> KillSwitch terminates pending instance

- Cargo.lock
- lucet-objdump/Cargo.toml
- lucet-objdump/src/main.rs
Over in #470, we discovered that `object` and `faerie` have different
approaches to writing relocations in shared objects.  In a nutshell,
`object`'s approach requires applying relocations to the shared object's
data whereas `faerie`'s does not (at least for the current structure of
`lucet-objdump`).
This change represents an intermediate step towards accommodating
`object`'s relocation approach by rewriting `lucet-objdump` to use
`object` instead of `goblin` for reading files.  `object` is a little
easier to work with, a little more abstract than `goblin`, and various
other bits of Lucet already use `object` anyway.
There are no differences in `lucet-objdump`'s output on a representative
file when `lucet-objdump` is compiled with and without this patch.
> use object instead of goblin in lucet-objdump

- lucet-runtime/lucet-runtime-internals/src/alloc/tests.rs
One of the things that surprised me in the `alloc` tests was that a failed instance still takes up the slot capacity of a region.  I've written a test that demonstrates this scenario.  
- If this behaviour is expected, then I'm glad to have a test to demonstrate that the behaviour is expected.  No other test seems to exercise this logic and I prefer not to leave things unsaid.
- If this behaviour is unexpected, then we can take other steps.
> Conveying expectations:  Bad instances take up capacity.

- lucet-runtime/lucet-runtime-internals/src/instance/execution.rs
- lucet-runtime/lucet-runtime-internals/src/instance/signals.rs
- lucet-runtime/lucet-runtime-tests/src/guest_fault.rs
- lucet-runtime/lucet-runtime-tests/src/timeout.rs
Over in #429 we adjusted `KillSwitch` to be useful in that a timeout before a guest begins is upheld, rather than ignored. As it turns out, our tests didn't cover one of the expectations we have around instance lifetimes: after a fault, instances _can_ be run without reset. Consequently, users of lucet-runtime that ran instances post-fault without reset (such as `lucet-spectest`) caught a bug: rerunning after a fault could cause us to panic in a way that aborts the process.
In normal guest exits we disable termination on the instance's `KillState`, then reset it to a new one so new `KillSwitch` can cancel execution for some eventual function call. To avoid the bad `KillState` state, we just needed to do the same when exiting through a signal handler, too.
The first commit here introduces …
> Faulted guests can run!

- Cargo.lock
- lucet-runtime/lucet-runtime-tests/Cargo.toml
- lucet-runtime/lucet-runtime-tests/src/guest_fault.rs
There was a bug in `illegal_instr_manuals_signal()` where the Lucet signal handler would remain installed for the remainder of the test suite execution. Somehow this wasn't causing any failures, but does if the test suite is run more than once.
To guard against this type of thing in the future, I added a wrapper to any tests that muck with the process's signal handlers to ensure that the handlers are the same before and after the test runs.
This is definitely a diff to view with whitespace diffs hidden, due to the indentation of the new closure wrapper.
> In the guest_fault suite, check that signal handlers are restored

- lucet-objdump/src/main.rs
Computing the total number of bytes in the trap manifest was using the
wrong thing, which resulted in too much data being read.  This might or
might not manifest as a problem, depending on how the trap sites were
laid out with respect to other data in the binary.
> fix parsing of trap manifests in lucet-objdump

- lucetc/src/compiler.rs
- lucetc/src/decls.rs
From a functionality standpoint, this is not strictly necessary.
However, it does two things: it exports less from the static library,
which seems like a good thing, and it encourages `cranelift-object` to
more closely match `cranelift-faerie` in terms of the relocations it
uses in the final output, which is good for #470.
> lucetc: declare more things as local

- Cargo.lock
- lucetc/Cargo.toml
- lucetc/src/compiler.rs
- lucetc/src/error.rs
- lucetc/src/output.rs
This commit makes `lucetc` use `cranelift-object`/`object` as its interface for writing out native objects.  The intent is that this moves `lucetc` closer to getting PE/COFF support "for free".
We had discussed providing a runtime switch for compatibility/risk reasons, but given that so much is going through `cranelift-module` now and the amount of `object`-specific code is minimal, I believe that providing a runtime switch is just extra complexity for no reason.  Happy to hear pushback on that.
> convert lucetc to use object as the I/O backend

- Makefile
This time, in a proper PR :grimacing: :pensive: 
See: https://doc.rust-lang.org/cargo/commands/cargo-build.html
```
--workspace
Build all members in the workspace.
--all
Deprecated alias for --workspace.
```
I don't expect `--all` to go away _soon_, but we might as well be sure not to rely on a deprecated alias.
> use `cargo build --workspace`

- lucetc/src/lib.rs
We have an explicit target triple that we should use here.
> fix lucetc error message about linker flags

- lucetc/src/lib.rs
`link.exe` uses `/out:$FILE` instead of `-o $FILE`.  We assume that
everybody else besides `*-pc-windows-msvc` uses the latter convention.
> fix linker output argument for windows

- Cargo.lock
- Dockerfile
- lucet-runtime/Cargo.toml
- lucet-runtime/lucet-runtime-internals/Cargo.toml
- lucet-runtime/lucet-runtime-internals/src/alloc/tests.rs
- lucet-runtime/lucet-runtime-internals/src/module.rs
- lucet-runtime/lucet-runtime-internals/src/region.rs
- lucet-runtime/lucet-runtime-internals/src/region/mmap.rs
- lucet-runtime/lucet-runtime-internals/src/region/uffd.rs
- lucet-runtime/src/c_api.rs
- lucet-runtime/src/lib.rs
- lucet-runtime/tests/entrypoint.rs
- lucet-runtime/tests/globals.rs
- lucet-runtime/tests/guest_fault.rs
- lucet-runtime/tests/host.rs
- lucet-runtime/tests/memory.rs
- lucet-runtime/tests/stack.rs
- lucet-runtime/tests/start.rs
- lucet-runtime/tests/strcmp.rs
- lucet-runtime/tests/timeout.rs
This first commit enables alloc tests for `UffdRegion`, adds a new test, and fixes some things:
- Instantiates the suite in `lucet_runtime_internals::alloc::tests` for `UffdRegion`
- Fixes early return issues in `UffdRegion` similar to #455
- Adds a test to show that the per-instance heap limit applies to runtime expansions, not just initial instantiation
- Refactors `validate_runtime_spec` to take the per-instance heap limit as an additional argument. This centralizes the logic for rejecting initially-oversized heap limits, and makes it clearer what's happening in each region's instantiation logic.
- Removes the `UffdRegion`'s assertion that signal stack size is a multiple of page size. Since the user can now control this as a parameter, we reject it gracefully when validating `Limits` …
> [PR into tyler/uffd-integration] Fixes uncovered during review of #492

- .github/workflows/mac-ci.yml
- .github/workflows/main.yml
- Dockerfile
- Makefile
we have run out of disk space on github actions. We're building an awful
lot of suff serially, so lets split them into many jobs so that each job
has some headroom.
* test-ci should just do a `profile = test` build. I'm not 100%
confident I got that right but lets run it and see.
* smoke testing benchmarks does a `profile = bench` build, so
we can move that to its own makefile target and job.
* smoke testing fuzz does a `profile = debug` build, so
we can move that to its own makefile target and job.
* cargo audit doesnt need to be in docker container. it can be its own
job in parallel. Just need stable rust and cargo-audit installed.
* docs build doesnt need to be in docker container. it can be its own
job in parallel. Just need stable rust and mdbook
> factor makefile & ci jobs to run more parallel jobs

- lucet-runtime/lucet-runtime-internals/src/instance.rs
- lucet-runtime/lucet-runtime-internals/src/instance/execution.rs
- lucet-runtime/lucet-runtime-internals/src/instance/signals.rs
- lucet-runtime/lucet-runtime-internals/src/instance/state.rs
- lucet-runtime/lucet-runtime-tests/src/timeout.rs
1. Overview
This patch changes where we re-initialize an instance's `KillState`
after completing an execution. This re-initialization, to review, is
required for upholding guarantees about the validity of a `KillSwitch`
with respect to an instance's lifetime.
2. Motivation
Previously, we reset the kill state in one of two places: (1) the lucet
context backstop `exit_guest_region`, and (2) the lucet signal handler,
`handle_signal` defined in
`lucet-runtime-internals/src/instance/signals.rs`.
The latter poses a potential problem, because neither `malloc` or `free`
are required to be async-signal-safe by POSIX.1 (see signal-safety(7)[1]
for more information on this topic).
This means that we should neither allocate or free a new kill state,
because `Arc` *does* in fact use heap …
> lucet-runtime-internals: do not reset kill state in signal handler

- Cargo.toml
- lucet-runtime/lucet-runtime-macros/src/lib.rs
- lucet-runtime/lucet-runtime-tests/src/entrypoint.rs
- lucet-runtime/lucet-runtime-tests/src/guest_fault.rs
- lucet-runtime/lucet-runtime-tests/src/host.rs
- lucet-runtime/lucet-runtime-tests/src/strcmp.rs
- lucet-runtime/lucet-runtime-tests/src/timeout.rs
- lucet-runtime/src/c_api.rs
- lucet-runtime/tests/guest_fault.rs
- lucet-runtime/tests/instruction_counting.rs
- lucet-runtime/tests/version_checks.rs
- lucet-wasi/tests/guests/duplicate_import.wat
- lucet-wiggle/generate/src/lib.rs
As part of the upgrade to rust 1.42, executables which export hostcalls through the usual methods (e.g. `lucet_wasi::export_wasi_funcs`) apparently broke, but only when compiling in release mode.
Adam determined that changing the Rc leak of the hostcall function pointers to `assert_ne!(fptr, null)` fixed the issue. Previously, I noticed that enabling LTO fixed the issue as well, but the assert_ne fix seems a lot more likely to keep working across changes to rustc and llvm.
```sh
cargo build --release -p lucetc -p lucet-wasi
./target/release/lucetc lucet-wasi/tests/guests/duplicate_import.wat --bindings lucet-wasi/bindings.json
./target/release/lucet-wasi a.out
```
Prior to this patch, `target/release/lucet-wasi` will fail to dlopen the module because the wasi hostcall symbols are missing, …
> Fix hostcalls when building in release mode

- .github/workflows/main.yml
- Makefile
- lucet-wasi/tests/test_helpers/mod.rs
- lucet-wasi/tests/tests.rs
- lucet-wiggle/tests/wasi.rs
Adds makefile targets and CI jobs to test in `--release` mode, and fixes all tests to work in that mode.
Optimizations run in release builds which often lead to dead-code-elimination or link-time garbage collection opportunities, and change how our runtime dynamic linking ends up working. This testing should prevent further regressions like we had when upgrading to rust 1.42.
> Add release mode testing to CI

- lucet-runtime/lucet-runtime-internals/src/alloc/mod.rs
- lucet-runtime/lucet-runtime-internals/src/alloc/tests.rs
- lucet-runtime/lucet-runtime-internals/src/instance.rs
- lucet-runtime/lucet-runtime-internals/src/module/sparse_page_data.rs
- lucet-runtime/lucet-runtime-internals/src/region/mmap.rs
- lucet-runtime/lucet-runtime-internals/src/sysdeps/mod.rs
- lucet-runtime/lucet-runtime-internals/src/sysdeps/unix.rs
I have this quixotic idea that most OS/arch-specific stuff should be able to live in `lucet_runtime_internals::sysdeps`; this patch is a first step along that path.  Ideally, adding Windows support can be boiled down to figuring out how to expose the right interfaces from `sysdeps` that everybody can implement.  Signals make this very tricky, among other things, but perhaps since Firefox doesn't care about signals + Lucet, the signal support for Windows can somehow be punted down the road.
Happy to hear thoughts about what might be a better path to structuring the codebase for Windows support.
> move `host_page_size` to sysdeps

- lucet-runtime/lucet-runtime-tests/src/guest_fault.rs
> remove pthread-related imports from guest_fault tests

- .circleci/config.yml
We currently are building up our real config on the `circleci-project-setup` branch, but adding this empty config will make the Github checks interface stop showing a failure due to a missing config on `master`.
> ⭕ Add an empty circleci config

- lucet-wiggle/src/lib.rs
Changes Wiggle's borrow of vmctx's heap to be just at the use-site of a GuestPtr.
The GuestMemory::base function, which is only called by GuestMemory::validate_size_align, is in turn used by `GuestPtr::as_raw`, `GuestType::read`, and `GuestType::write`. The latter two only keep the resulting pointer for the lifetime of their stack frame. GuestPtr::as_raw does keep the resulting pointer alive as part of the `*mut [T]` returned, so that borrow *could* possibly be alive across the yield, though the current safety properties in the docs explicitly say it cannot be.
To resolve that safety hole, we need to move to a whole-hostcall GuestBorrows as we discussed on the call with Alex on monday. Will work on that as a subsequent PR upstream. For now, this means we can yield in wiggle without an …
> lucet-wiggle: only borrow heap inside GuestMemory::base

- .circleci/config.yml
- .github/workflows/main.yml
- Dockerfile
- Makefile
- helpers/lucet-toolchain-tests/objdump.sh
- helpers/lucet-toolchain-tests/signature.sh
This patch ports our existing Github Actions CI to CircleCI, which allows us to test programs that use the `userfaultfd` syscall on Linux. Also, we're paying CircleCI to use their big machines and Docker layer cache, so CI overall will be much faster.
A significant change from the Github Actions setup is to revert to a single build job, rather than having a proliferation of smaller jobs. The latter approach was necessary to achieve good performance with Actions, but the way CircleCI's Docker caching works, the single job is much more cost effective.
These jobs cache the Cargo-generated `/target` directory for branch builds, which substantially helps run times. Cargo is pretty aggressive about rebuilding when files, environment variables, or moon phases change, but the cache is completely …
> ⭕ Add full CircleCI configuration

- .github/workflows/main.yml
- Makefile
Currently we are using CircleCI to test `lucet-runtime`.  We've been needing a way to test the `userfaultfd` implementation of Regions.  The tests can't run on the containers supplied by GitHub Actions because the containers don't have the privileges necessary to use the kernel mechanisms for `userfaultfd`.
The GitHub Actions tests are still failing, tho.  And I worry about conveying a wrong message in CI Results.  So I'd like to remove the failing tests that are tested by CircleCI.
> Remove `lucet-runtime` from crates tested by GitHub Actions

- .circleci/config.yml
- We can't get the `large` machine size without contacting support, but since the macOS build is   already faster than the Linux build, I see no reason to spend more credits on the bigger size.
- Builds have been observed non-deterministically failing due to lack of disk space, and so the   CircleCI docs have this amazing workaround where you delete the iOS simulator files if you don't   need them.
> ⭕🍎 Improve macOS CircleCI config

- .github/actions/test/action.yml
- .github/workflows/main.yml
this will make it apply to each call of the makefile, and set the
environment inside the Docker container rather than outside. See also #528
> github config: move `env` that excludes crates into action

- lucet-runtime/src/lib.rs
I would like to make the `AllocStrategy` public so that I may use it in code leveraging the `lucet-runtime`.
> Make AllocStrategy public

- helpers/install.sh
Also look for LLVM in `/usr/lib/llvm-*`, and avoid a warning if the shell doesn't define a `$SHELL` environment variable.
> install.sh: wasi/core.h was renamed to wasi/api.h

- lucet-wasi/tests/guests/getrusage.c
The for loop was optimized out at any optimization level.
Also remove a temporary comment.
> Do something in the getrusage test

- docs/src/Compiling-on-Linux.md
- docs/src/Compiling-on-macOS.md
- docs/src/Compiling.md
Remove the copy of the `Dockerfile` used for CI in order to discourage usage of that Docker file for other purposes..
Also, compiling `wasi-libc` is not needed any more.
> Doc: recommend usage of wasi-sdk 10 instead of wasi-sdk 8

- Cargo.lock
- lucet-module/Cargo.toml
- lucet-module/src/traps.rs
- lucet-runtime/include/lucet_types.h
- lucet-runtime/lucet-runtime-internals/src/c_api.rs
- lucet-validate/Cargo.toml
- lucet-wasi/Cargo.toml
- lucet-wasi/generate/Cargo.toml
- lucet-wiggle/Cargo.toml
- lucet-wiggle/generate/Cargo.toml
- lucet-wiggle/generate/src/lib.rs
- lucet-wiggle/macro/Cargo.toml
- lucet-wiggle/src/lib.rs
- lucetc/Cargo.toml
- lucetc/src/traps.rs
Updates wasmtime past 0.16.0 - supercedes #510 
* lucet-wiggle gets updates for wiggle automatic borrow checking
* update wasmparser dep
* update trap enumerations to keep in sync with wasmtime.
> Integrate wiggle changes for automatic borrow checking

- lucet-runtime/lucet-runtime-internals/src/alloc/mod.rs
Add a few bits of polish to AllocStrategy so that it's easier to use elsewhere.  
When AllocStrategy is used by a data structure passed across multiple threads, it would be handy to have both the AllocStrategy and its inner Mutex equipped with `Send`.  In times where one wants to use `#[derive(Debug)]`, it would also be handy for AllocStrategy to have an `impl` of `Debug`.
> Add a few bits of polish to AllocStrategy so that it's easier to use elsewhere

- .circleci/config.yml
- .github/workflows/mac-ci.yml
- Dockerfile
- lucet-module/src/signature.rs
Upgrade to wasi-sdk-11 in the CI scripts.
Also, add a CACHE_VERSION environment variable to the circle ci macos cache key, because the cache has gotten too big to successfully restore and circle-ci's honest answer to that glaring flaw in their product is "just roll your own cache invalidation system on the spot, itll be fine" which is pretty cool
> upgrade to wasi-sdk-11

- Cargo.lock
- lucet-module/Cargo.toml
- lucet-validate/Cargo.toml
- lucet-wasi/Cargo.toml
- lucet-wasi/generate/Cargo.toml
- lucet-wasi/generate/src/lib.rs
- lucet-wiggle/Cargo.toml
- lucet-wiggle/generate/Cargo.toml
- lucet-wiggle/generate/src/config.rs
- lucet-wiggle/generate/src/lib.rs
- lucet-wiggle/macro/Cargo.toml
- lucet-wiggle/macro/src/lib.rs
- lucet-wiggle/src/lib.rs
- lucetc/Cargo.toml
- lucetc/src/decls.rs
- lucetc/src/function.rs
- lucetc/src/module.rs
- lucetc/src/runtime.rs
- lucetc/src/stack_probe.rs
- lucetc/src/types.rs
Update wasmtime dep to include improvements to wiggle to support error transformations and the switch to use `tracing`:
https://github.com/bytecodealliance/wasmtime/pull/1796
Had to pull in some cranelift changes in the process - cranelift-wasm now keeps track of both the wasm function type and the cranelift signature, ends up being a net win that gets rid of some fallible code where we had to reverse-engineer the wasm function type back out of the signature. thank you @fitzgen!
> integrate wiggle tracing

- lucetc/src/load.rs
Once upon a time `wabt::Error` had no way to access the inner `wabt::ErrorKind`. In those days, I'd noticed that `Error` was a struct that contained only an `ErrorKind`, so this transmute was a hack to get the `ErrorKind` and the corresponding message so we could print that out while `wabt` was being tweaked to make this doable safely.
`wabt` long since has been tweaked to make this doable safely.
> Remove a no-longer-necessary transmute

- lucet-runtime/lucet-runtime-internals/src/future.rs
- lucet-runtime/lucet-runtime-internals/src/instance.rs
- lucet-runtime/lucet-runtime-tests/src/async_hostcall.rs
This godawful type signature enables callers to make sure Wasm execution happens on a blocking thread, for example by passing `|f| tokio::task::spawn_blocking(f)` as the `wrap_blocking` argument.
Renamed `run_await` to `block_on` for consistency with other async libraries.
> Add `wrap_blocking` argument to `run_async`; rename `run_await`

- .cargo/config
- Cargo.lock
- lucet-wasi-fuzz/Cargo.toml
- lucet-wasi-fuzz/src/main.rs
- lucet-wasi/tests/test_helpers/mod.rs
- lucet-wasi/tests/tests.rs
This uses a branch on wasmtime that's based on the wasmtime revision in this branch. I will be doing a PR with the same contents into wasmtime main once I write some docs for it.
> Use draft new wasi-common virtual pipe interface

- .circleci/config.yml
- Makefile
This should prevent the cache of the `/target` directory from accruing complete sets of artifacts from multiple `rustc` versions over time.
This patch also fixes the use of `{{ .Environment.CACHE_VERSION }}` so that it applies to Linux, and so that it forms proper prefixes in the macOS cache keys.
> 📉 Reduce CircleCI cache sizes by keying on `rust-toolchain`

- lucet-runtime/include/lucet_types.h
- lucet-runtime/lucet-runtime-internals/src/c_api.rs
- lucet-runtime/lucet-runtime-internals/src/instance.rs
- lucet-runtime/lucet-runtime-macros/src/lib.rs
- lucet-runtime/lucet-runtime-tests/src/guest_fault.rs
This prevents panics that aren't intentionally initiated by the Lucet runtime from attempting to unwind across Wasm stack frames. When #254 lands, this will no longer be necessary, but until then this allows us to safely transport the unknown panic payload across the FFI boundary so that panicking can resume on the other side.
> 💢 Package unknown hostcall panics into termination details

- Makefile
- lucet-objdump/Cargo.toml
- lucet-runtime/Cargo.toml
- lucet-validate/Cargo.toml
- lucet-wasi/Cargo.toml
- lucetc/Cargo.toml
Several of the project's `Cargo.toml` files contained `[package.metadata.deb]` sections that described how to create a deb package with `cargo-deb`. These packages were all given the Fastly-specific `fst-` prefix for their package name and installation path (e.g. `/opt/fst-lucetc/...`). We do not use them inside Fastly anymore, and I'm not aware of any external users who depend on them either.
> Delete `cargo deb` packaging metadata

- lucetc/lucetc/main.rs
- lucetc/lucetc/options.rs
- lucetc/src/error.rs
- lucetc/src/lib.rs
- lucetc/src/load.rs
wat translation is a potential attack vector, since it happens in the C++ `wabt` library, so we want a way to turn it off if required.
```sh
[lucet]% cargo run -p lucetc -- lucetc/tests/wasm/globals_export.wat --no-translate-wat
Finished dev [unoptimized + debuginfo] target(s) in 0.06s
Running `target/debug/lucetc lucetc/tests/wasm/globals_export.wat --no-translate-wat`
Error: Input does not have Wasm preamble
```
> lucetc: add command line option to disable wat translation

- lucet-runtime/lucet-runtime-internals/src/error.rs
- lucet-runtime/lucet-runtime-internals/src/module/dl.rs
"The #[from] attribute always implies that the same field is #[source], so you don't ever need to specify both attributes." - https://docs.rs/thiserror/1.0.20/thiserror/
> thiserror::Error derivations: #[from] implies #[source]

- lucet-wasi/Cargo.toml
the default features in wasi-common are to set the `tracing/log` feature
flag, which directs all tracing's events to log ecosystem backends.
Lucet is all-in on the tracing ecosystem.
> lucet-wasi: set wasi-common default-features=false

- Cargo.lock
- lucet-module/Cargo.toml
- lucet-module/src/traps.rs
- lucet-runtime/include/lucet_types.h
- lucet-runtime/lucet-runtime-internals/src/c_api.rs
- lucet-wasi/Cargo.toml
- lucet-wasi/generate/Cargo.toml
- lucet-wiggle/Cargo.toml
- lucet-wiggle/generate/Cargo.toml
- lucet-wiggle/macro/Cargo.toml
- lucet-wiggle/macro/src/lib.rs
- lucet-wiggle/tests/wasi.rs
- lucetc/Cargo.toml
- lucetc/src/compiler.rs
- lucetc/src/decls.rs
- lucetc/src/function.rs
- lucetc/src/module.rs
- lucetc/src/runtime.rs
- lucetc/src/stack_probe.rs
- lucetc/src/traps.rs
- lucetc/src/types.rs
- lucetc/src/validate.rs
- lucetc/tests/wasm.rs
* Lots of version bumps
* new cranelift trapcode
* some types are now provided by cranelift-wasm instead of wasmparser
* wiggle macro path resolution works differently now.
> pull in latest wasmtime 0.19.1 / cranelift 0.66

- benchmarks/lucet-benchmarks/src/modules.rs
- lucet-runtime/lucet-runtime-internals/src/vmctx.rs
- lucet-runtime/lucet-runtime-macros/src/lib.rs
- lucet-runtime/lucet-runtime-tests/src/entrypoint.rs
- lucet-runtime/src/c_api.rs
This was a programming error introduced in the transition between the `lucet_hostcalls!` macro and the `#[lucet_hostcall]` attribute.
The expansion of the code in the attribute called the annotated function from within a `catch_unwind` without modifying its ABI. Since it is UB to unwind from a non-Rust ABI function, release mode optimizations would elide the code which would otherwise handle an unwind from the function. This caused the process to abort if the function ever _did_ unwind, since the system unwinding runtime would reach the end of the guest stack without finding any frames willing to handle the exception.
I believe this behavior was very difficult, if not impossible, to observe in practice with the current state of the Lucet codebase. The only unwinding that these functions …
> ☢️ Remove UB from `extern "C"` ABI on annotated hostcalls

- CHANGELOG.md
- lucet-runtime/include/lucet_types.h
- lucet-runtime/lucet-runtime-internals/src/c_api.rs
- lucet-runtime/lucet-runtime-internals/src/instance.rs
- lucet-runtime/lucet-runtime-internals/src/region.rs
- lucet-runtime/lucet-runtime-internals/src/region/mmap.rs
- lucet-runtime/lucet-runtime-internals/src/region/uffd.rs
- lucet-runtime/lucet-runtime-internals/src/vmctx.rs
- lucet-runtime/lucet-runtime-tests/src/entrypoint.rs
- lucet-runtime/src/c_api.rs
This new option determines whether to terminate the guest with a new `TerminationDetails::HeapOutOfMemory` variant when `memory.grow` fails, rather than returning `-1`. It is disabled by default, but can be set via `InstanceBuilder` or directly on the `Instance`.
This behavior deviates from the WebAssembly spec, but is useful in practice for determining when guest programs fail due to an exhausted heap.
Most languages will compile to code that includes an `unreachable` instruction if allocation fails, but this same instruction might also appear when other types of assertions fail, `panic!()` is called, etc. Terminating allows the error to be more directly identifiable.
> 🈵 Add an option to terminate the runtime when `memory.grow` fails

- lucet-wasi/generate/src/config.rs
- lucet-wasi/generate/src/lib.rs
in the process, convert the option parsing to use kw & lookahead like its friends do in wiggle-generate
> lucet-wasi-generate: accept pre_hook and post_hook as proc macro arguments

- Cargo.lock
- lucet-wasi/Cargo.toml
- lucet-wasi/src/main.rs
required for e.g. RUST_LOG=wasi-common=trace
> lucet-wasi executable: add tracing_subscriber

- .github/workflows/fuzz.yml.disabled
- .github/workflows/mac-ci.yml
In accordance with this advisory it's recommended we move to a
different scheme of setting env vars and updating PATH:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Thank you @alexcrichton for bringing this to my attention
> use $GITHUB_PATH rather than ##[add-path]

- Cargo.lock
- lucet-runtime/Cargo.toml
Version 0.3.5 includes dependencies with vulnerabilities:
RUSTSEC-2020-0060 (use-after-free)
RUSTSEC-2020-0059 (data race in safe code)
> Update futures-executor to version 0.3.7

- docs/src/Compiling-on-Linux.md
Fix 'typo' linking path for "wasi sysroot"
`sudo ln -s /opt/wasi-sdk-*/share/wasi-sysroot /opt/wasi-sysroot`
=>
`sudo ln -s /opt/wasi-sdk-11.0/share/wasi-sysroot /opt/wasi-sysroot`
> Compiling on linux: MD; fix typo for linking

- lucetc/src/compiler.rs
The verifier can end up taking a significant chunk of time. On a local
test case this change decreases the CPU time used by lucetc from 30s to
6.5s.
This is take 2 of https://github.com/bytecodealliance/lucet/pull/603 as a PR from this repo's branch to see if CI triggers well.
> Don't enable the Cranelift verifier in release mode

- Cargo.lock
- lucetc/src/compiler.rs
- lucetc/src/decls.rs
- lucetc/src/function.rs
- lucetc/src/module.rs
- lucetc/src/table.rs
Following up on some API changes to the environment traits in
bytecodealliance/wasmtime#2115, this PR updates the git version of the
`wasmtime` submodule and updates `lucetc` accordingly.
The changes are basically just renamings, along with a removal of a
RelocSink trait method that was previously unused.
(This is a re-creation of #609, merging from a branch in the main repo rather than my fork.)
> Update wasmtime to latest version.

- lucet-runtime/lucet-runtime-internals/src/module/dl.rs
- lucet-runtime/lucet-runtime-internals/src/region/uffd.rs
- lucet-runtime/src/c_api.rs
- lucet-runtime/src/lib.rs
- lucet-runtime/tests/memory.rs
- lucet-wasi/src/main.rs
Two changes, one PR:
1. lucet-runtime::DlModule load now optionally enforces version match
This check exists to make sure that lucetc and lucet-runtime are built
against the same revision of lucet-module - the use of serde depends
on both sides defining types the same.
This check can be overridden for cases where the user's runtime needs to
load modules built with a different lucetc. The user is responsible for
ensuring that the modules were created with the same lucet-module type
definitions.
1. lucet-runtime: change uffd configurations to have many more options.
The user can now configure the strategy of stack initialization and heap initialization as well as the page size. also, configurations are given by a struct now instead of a trait.
> dlmodule version checks optional, uffd configuration options expanded

- .circleci/config.yml
- Cargo.lock
- Makefile
- lucet-runtime/lucet-runtime-tests/src/guest_fault.rs
- lucet-runtime/lucet-runtime-tests/src/stack.rs
- lucetc/Cargo.toml
The new x86-64 backend in Cranelift is now able to run all Lucet tests,
and has shown better performance (compile-time and run-time) than the
current backend. This PR adds a Cargo feature to lucetc to build with
the new backend, and modifies the Makefile and CircleCI config to run
tests with the new backend as well, in order to ensure that it continues
to work.
> Add new x64 backend as lucetc option, and add to CI runs.

- Cargo.lock
- helpers/lucet-toolchain-tests/signature.sh
- lucet-module/Cargo.toml
- lucet-module/src/signature.rs
- lucet-objdump/Cargo.toml
- lucet-objdump/src/main.rs
Having different versions of the same dependency is not a good idea, and `lucet-module` couldn't see the `lucet_module_data` symbol any more on macOS.
This repairs signatures on macOS.
> Update the object crate to the same version as wasmtime

- lucet-module/src/runtime.rs
- lucet-runtime/include/lucet_vmctx.h
- lucet-runtime/lucet-runtime-internals/src/future.rs
- lucet-runtime/lucet-runtime-internals/src/instance.rs
- lucet-runtime/lucet-runtime-internals/src/instance/state.rs
- lucet-runtime/lucet-runtime-internals/src/vmctx.rs
- lucet-runtime/lucet-runtime-tests/src/async_hostcall.rs
- lucet-runtime/src/c_api.rs
- lucet-runtime/tests/instruction_counting.rs
- lucet-runtime/tests/instruction_counting/long_loop.wat
- lucet-runtime/tests/instruction_counting/long_loop_start.wat
- lucetc/src/compiler.rs
- lucetc/src/error.rs
- lucetc/src/function.rs
- lucetc/src/runtime.rs
- lucetc/tests/wasm.rs
This modifies the instruction-counting mechanism to track an
instruction-count bound as well; and when a bound is set, the Wasm guest
will make a hostcall to yield back to the host context.
This is all placed under the `run_async()` function, so bounded-execution
yields manifest as futures that are immediately ready to continue execution.
This should give an executor main loop a chance to do other work at regular
intervals.
> Add a "bounded runtime" mode to guest execution.

- Cargo.lock
This pulls in a fix to a codegen bug with the new x64 backend.
> Update wasmtime dependency to include bytecodealliance/wasmtime#2576.

- CHANGELOG.md
- Cargo.lock
- lucet-runtime/lucet-runtime-internals/Cargo.toml
- lucet-runtime/lucet-runtime-internals/src/instance.rs
- lucet-wasi/src/main.rs
- lucet-wasi/tests/test_helpers/mod.rs
- lucet-wiggle/generate/src/lib.rs
another small one for the day: by passing `wiggle::Trap` we can ~force~ encourage users of `lucet` to handle the types that can arrive from a `TerminationDetails::Provided` by passing `wiggle::Trap` directly. then, users can be certain that the only types that can show up are their own provided types from `lucet_hostcall_terminate`, or `wiggle::Trap` via the wiggle bindings.
> just pass the underlying wiggle::Trap to lucet_hostcall_terminate

- lucet-runtime/lucet-runtime-internals/src/future.rs
- lucet-runtime/lucet-runtime-internals/src/instance.rs
- lucet-runtime/lucet-runtime-internals/src/instance/state.rs
- lucet-runtime/lucet-runtime-internals/src/vmctx.rs
- lucet-runtime/lucet-runtime-macros/src/lib.rs
- lucet-runtime/lucet-runtime-tests/guests/async_hostcall/bindings.json
- lucet-runtime/lucet-runtime-tests/guests/async_hostcall/hostcall_block_on.c
- lucet-runtime/lucet-runtime-tests/src/async_hostcall.rs
- lucet-runtime/src/lib.rs
- lucet-runtime/tests/instruction_counting.rs
This PR replaces the `async fn run_async_internal()` with a custom implementation of Future.
Advantages:
- Significantly less unsafe code than the original implementation of run_async (just one line, used for pinning the future)
a much sounder execution model: the future is executed from within the guest! When host execution is desired tokio::spawn or similar works from within block_on
- Support for defining async fn hostcalls without ever manually calling block_on
- Near-zero overhead for polling an immediately-ready future (only the cost of an Arc.clone()). For example, a future like `async { 5 }` would immediately resolve to 5, without requiring a yield to the host.
- Support for regular yielding from an async execution, even from within block_on
- A defined type for the future …
> Refactor run_async to use custom Future implementation 

- helpers/install.sh
`sightglass` and `wasmonkey` are now maintained independently, so don't try to install them.
> Don't try to install packages we don't include any more

- Cargo.lock
- lucet-wiggle/generate/Cargo.toml
- lucet-wiggle/generate/src/lib.rs
- lucet-wiggle/macro/Cargo.toml
- lucetc/Cargo.toml
- lucetc/src/validate.rs
- lucetc/tests/wasm.rs
bumps the wasmtime submodule, which in turn pulls in witx 0.9. Fixes in lucet-wiggle and lucetc's witx validator to use the new AST.
> use witx 0.9

- lucet-runtime/tests/instruction_counting/br_table_loop.wat
- lucetc/src/function.rs
Previously, we did not insert instruction count flush/check sequences on
backedges if they arose from a br_table instruction. This patch ensures
that we check the instruction count in such a case.
> Instruction counting: handle br_table backedges.

- lucet-runtime/lucet-runtime-internals/src/future.rs
- lucet-runtime/lucet-runtime-internals/src/instance.rs
- lucet-runtime/lucet-runtime-internals/src/instance/state.rs
- lucet-runtime/lucet-runtime-internals/src/vmctx.rs
- lucet-runtime/lucet-runtime-macros/src/lib.rs
- lucet-runtime/lucet-runtime-tests/guests/async_hostcall/bindings.json
- lucet-runtime/lucet-runtime-tests/guests/async_hostcall/hostcall_block_on.c
- lucet-runtime/lucet-runtime-tests/src/async_hostcall.rs
- lucet-runtime/src/lib.rs
- lucet-runtime/tests/instruction_counting.rs
This reverts commit bf24022cc5e9c7e26ae12dd54c16fdbb26a45ddd, reversing
changes made to ddaf91e4875adfb4912be47f51620c6ffafd818d.
Unfortunately, in testing, we discovered that #626 has unsound interactions with asynchronous signal handling. We want to find a sound way to get these changes back in, but we need to revert the merge while we figure that out.
626 introduced a change to `lucet_runtime_internals::State` where a variant now contains an Arc:
```
Running {
async_context: Option<std::sync::Arc<AsyncContext>>,
}
```
When a signal handler terminates an instance, https://github.com/BytecodeAlliance/lucet/blob/main/lucet-runtime/lucet-runtime-internals/src/instance/signals.rs#L310 will drop this Arc from a signal context, which will in turn call `free` on the underlying memory. If the …
> Revert #626 (Refactor run_async custom Future): unsound

- .circleci/config.yml
- lucetc/Cargo.toml
- lucetc/src/compiler.rs
After sufficient testing, we're confident that the new x64 backend does
not have any correctness issues relative to the old backend; and because
it generates better code, we would like to switch the default. This PR
will cause `lucetc` to use the new backend by default. Building `lucetc`
with the `old-x64-backend` Cargo feature will swap the old backend in
again. This PR also removes the separate new-backend CI tests.
> Make the new Cranelift x64 backend the default.

- lucet-runtime/lucet-runtime-internals/src/alloc/mod.rs
- lucet-runtime/lucet-runtime-internals/src/region/mmap.rs
- lucet-runtime/lucet-runtime-internals/src/region/uffd.rs
On Linux 5.7+, the kernel retries faults which is causing the uffd tests to
hang because the `UffdRegion` wakes invalid page accesses expecting the kernel
to signal `SIGBUS` rather than retry the fault.
This fix attempts to work around the recent kernel behavior by changing the
page protection to `NONE` for an invalid page access. The access is reset when
the `Alloc` is dropped or when the instance is reset.
> Fix wake in `UffdRegion` for invalid page access on Linux 5.7+.

- SECURITY.md
At a meeting last week, the Bytecode Alliance board resolved to introduce a BA security policy, and apply it to some core projects to begin with, including Lucet.
> Refer to BA security policy

- Cargo.lock
- lucet-module/Cargo.toml
- lucetc/Cargo.toml
- lucetc/src/module.rs
- lucetc/src/sparsedata.rs
- lucetc/src/table.rs
Pull in the fix for CVE-2021-32629: https://github.com/bytecodealliance/wasmtime/pull/2919
As well as several other changes to cranelift-wasm & related interfaces.
> update to wasmtime main with fix for CVE-2021-32629

- .gitmodules
- Cargo.lock
- lucet-module/Cargo.toml
- lucet-runtime/lucet-runtime-internals/Cargo.toml
- lucet-wasi-fuzz/Cargo.toml
- lucet-wasi/Cargo.toml
- lucet-wiggle/Cargo.toml
- lucet-wiggle/generate/Cargo.toml
- lucet-wiggle/macro/Cargo.toml
- lucetc/Cargo.toml
Lucet is nearing EOL so we no longer need to track changes between releases in wasmtime. In case we do, we will use `[patch]` in Cargo.toml for a path or git dependency.
Having path dependencies in Lucet is causing integration headaches downstream, because you cannot `[patch]` over a path!
This PR removes the wasmtime submodule, and changes all deps to the latest crates.io release: cranelift-* is at 0.75.0, and the rest are at 0.28.0.
> remove wasmtime submodule, depend on latest wasmtime packages from crates.io

- Cargo.lock
- lucet-wiggle/generate/Cargo.toml
- lucet-wiggle/macro/Cargo.toml
- lucetc/Cargo.toml
The 0.9.1 release of witx most importantly includes
WebAssembly/WASI#434, which is a bug-fix affecting transitive imports in
witx documents.
This updates `lucetc`, `lucet-wiggle-generate`, and `lucet-wiggle-macro`'s dependencies relying on 0.9.0.
> Update witx dependencies

- Cargo.lock
- lucetc/Cargo.toml
- lucetc/lucetc/main.rs
- lucetc/lucetc/options.rs
- lucetc/src/compiler.rs
- lucetc/src/error.rs
- lucetc/src/lib.rs
- lucetc/tests/wasm.rs
This commit brings in VeriWasm, a static analysis tool that
independently verifies the sound heap-sandboxing and other properties of
machine code generated by Cranelift as used by Lucet. It adds an option
`--veriwasm` to the compiler `lucetc` so that, in concert with changes
recently made to VeriWasm and Cranelift, we can verify generated code in
memory, right after we generate it, and with reasonable overhead
(measured at ~30% additional compile time for some simple test cases).
This PR currently refers to my fork of VeriWasm as a submodule; the fork
has additional work on top of upstream that was reviewed internally by
@iximeow. Once we work out where this should live permanently, we can
update the submodule location, but this should be good enough for review.
> Integrate VeriWasm.

- Cargo.lock
cargo update -p: pin-project-lite sha2 crossbeam-epoch tokio
> fix cargo audit failures

- Cargo.lock
- docs/lucet-runtime-example/Cargo.toml
- docs/lucet-runtime-example/src/main.rs
> lucet-runtime-example: fix regression from #655

- Cargo.lock
- fuzz/Cargo.toml
- fuzz/fuzz_targets/veriwasm.rs
This fuzz target tests the property: any Wasm module that Lucet can
compile should produce an artifact that validates with VeriWasm. We are
looking for both "false positive" bugs in VeriWasm, i.e. compilation
results which are correct but which the validator can't handle, as well
as "true positive" validator errors that result from a genuine Lucet
miscompilation. If we see neither, then we have some more confidence
that both (i) Lucet is less likely to have heap-soundness bugs, and (ii)
VeriWasm is solid enough that one could consider requiring it to pass
before using a module.
> Add fuzz target to test VeriWasm validation.

- Cargo.lock
- lucet-module/Cargo.toml
- lucet-runtime/lucet-runtime-internals/Cargo.toml
- lucet-wasi-fuzz/Cargo.toml
- lucet-wasi/Cargo.toml
- lucet-wasi/src/main.rs
- lucet-wasi/tests/tests.rs
- lucet-wiggle/Cargo.toml
- lucet-wiggle/generate/Cargo.toml
- lucetc/Cargo.toml
- lucetc/tests/wasm.rs
Wasmtime & cranelift just made a new crates.io release. This upgrades Lucet to use them.
> upgrade to wasmtime 0.29, cranelift 0.76

- lucet-runtime/lucet-runtime-internals/src/region/uffd.rs
- lucet-runtime/lucet-runtime-tests/guests/memory/zero_memory.wat
- lucet-runtime/tests/memory.rs
* bugfix in the eager heap initialization: guard against initializing zero-sized memory. the zeropage ioctl will helpfully return EINVAL when this code path is exercised with initial_size = 0, e.g. when your wasm has `(memory (export "memory") 0)`
* add better testing coverage, checking the existing uffd test with both lazy (default, as before) and eager heap disposition, and add a test specifically for the bug fixed above.
* update `impl Default for UffdConfig` to the values we use in production.
> uffd: fix eager heap init bug, add testing, update defaults to reflect production

- Cargo.lock
- Dockerfile
- lucet-spectest/Cargo.toml
- lucetc/Cargo.toml
This updates lucet to use the most up-to-date version of VeriWasm that runs clean on lucet's fuzzer.
> Update VeriWasm version

- Cargo.lock
which has bugfixes to work correctly on linux 5.11 and above, which is
required for github's ubuntu-latest builder as of this morning
> `cargo update -p userfaultfd` to 0.4.2

- lucet-runtime/lucet-runtime-internals/src/error.rs
> fix for `semicolon_in_expressions_from_macros` warning in lucet_bail

- Cargo.lock
- Cargo.toml
- lucet-module/Cargo.toml
- lucet-runtime/lucet-runtime-internals/Cargo.toml
- lucet-wasi-fuzz/Cargo.toml
- lucet-wasi/Cargo.toml
- lucet-wiggle/Cargo.toml
- lucet-wiggle/generate/Cargo.toml
- lucetc/Cargo.toml
Just some dep updates.
We can get rid of the [patch] that we needed for the forgotten cranelift API in 0.31.0
> wasmtime 0.32
